#include "core/Strings.h"
#include <QMap>
#include <QMetaEnum>

// ─────────────────────────────────────────────────────────────────────────────
// German strings
// ─────────────────────────────────────────────────────────────────────────────
static const QMap<StringKey, QString> s_de = {
    { StringKey::MenuFile,              "Datei" },
    { StringKey::MenuView,              "Ansicht" },
    { StringKey::MenuSettings,          "Einstellungen" },
    { StringKey::MenuOpenFolder,        "Ordner öffnen…" },
    { StringKey::MenuRefresh,           "Neu laden (R)" },
    { StringKey::MenuQuit,              "Beenden" },
    { StringKey::MenuToggleOptions,     "Optionen ein/aus (Alt+S)" },
    { StringKey::MenuSettingsItem,      "Einstellungen…" },
    { StringKey::MenuLanguage,          "Sprache" },
    { StringKey::MenuVideoPlayback,     "Video-Wiedergabe" },
    { StringKey::MenuVideoNative,       "Nativ" },
    { StringKey::MenuVideoExternal,     "Externer Player" },

    { StringKey::FilterAudio,           "Audio" },
    { StringKey::FilterMedia,           "Medien" },
    { StringKey::FilterDate,            "Datum" },
    { StringKey::FilterName,            "Name" },
    { StringKey::FilterTags,            "Tags" },
    { StringKey::FilterFileSize,        "Dateigröße" },
    { StringKey::FilterTagModeAnd,      "UND" },
    { StringKey::FilterTagModeOr,       "ODER" },
    { StringKey::FilterTagModeNur,      "NUR" },
    { StringKey::FilterTagModeInklusiv, "INKLUSIV" },


    { StringKey::SettingsTitle,         "Einstellungen" },
    { StringKey::SettingsTabGeneral,    "Allgemein" },
    { StringKey::SettingsTabDesign,     "Design" },
    { StringKey::SettingsLanguageLabel, "Sprache:" },
    { StringKey::SettingsOk,            "OK" },
    { StringKey::SettingsCancel,        "Abbrechen" },
    { StringKey::SettingsTagDelete,     "Tag löschen" },

    { StringKey::MetaTitle,         "Datum bearbeiten" },
    { StringKey::MetaReset,         "Zurücksetzen" },

    { StringKey::TagBarPlaceholder,     "Tag hinzufügen…" },
    { StringKey::TagBarDropdownHeader,  "Tag hinzufügen" },

    { StringKey::CatPanelAddCategory,   "Neue Kategorie" },
    { StringKey::CatPanelNewSubcategory,"Neue Unterkategorie" },
    { StringKey::CatPanelRename,        "Umbenennen" },
    { StringKey::CatPanelDelete,        "Kategorie löschen" },
    { StringKey::CatPanelSetColor,      "Einheitsfarbe setzen" },
    { StringKey::CatPanelNewTag,        "Neuer Tag" },


    { StringKey::FilterCatNewName,      "Neuer Name:" },
    { StringKey::FilterTagRenamePrompt, "Tag umbenennen" },

    { StringKey::SettingsTabCategories,  "Kategorien" },
    { StringKey::SettingsCatNewLabel,    "Name:" },
    { StringKey::SettingsCatRenameTitle, "Kategorie umbenennen" },
    { StringKey::SettingsTagColorTitle,  "Tag-Farbe" },

    { StringKey::SettingsDesignBaseColors,      "Grundfarben" },
    { StringKey::SettingsDesignBgGradient,      "Hintergrund-Verlauf" },
    { StringKey::SettingsDesignAccent,          "Akzent" },
    { StringKey::SettingsDesignAccentSolid,     "Einfarbig" },
    { StringKey::SettingsDesignAccentGradient,  "Verlauf" },
    { StringKey::SettingsDesignTileTransparent, "Transparent" },
    { StringKey::SettingsDesignExportTitle,     "Theme exportieren" },
    { StringKey::SettingsDesignImportTitle,     "Theme importieren" },

    // Converter
    { StringKey::ConverterTagToSubcat,    "Tag → Unterkategorie" },
    { StringKey::ConverterSubcatToTag,    "Unterkategorie → Tag" },
    { StringKey::ConverterTagToCat,       "Tag → Kategorie" },
    { StringKey::ConverterCatToTag,       "Kategorie → Tag" },
    { StringKey::ConverterSubcatToCat,    "Unterkategorie → Kategorie" },
    { StringKey::ConverterCatToSubcat,    "Kategorie → Unterkategorie" },

    // Design – PDF viewer / sidebar / button colors

    // Uniform-color UI (replaces hardcoded German strings)

    // Hauptfenster-Leisten

    // Converter – lokalisierte Hinweistexte

    // PdfViewer – lokalisierte Texte

    // Saved Folders / Bookmarks
    { StringKey::MenuBookmarks,          "Ordner" },
    { StringKey::MenuBookmarksEmpty,     "(keine gespeicherten Ordner)" },
    { StringKey::BookmarkAdd,            "Ordner hinzufügen" },
    { StringKey::BookmarkEdit,           "Bearbeiten" },
    { StringKey::BookmarkDelete,         "Löschen" },
    { StringKey::BookmarkPathLabel,      "Pfad:" },
    { StringKey::BookmarkBrowse,         "Durchsuchen…" },

    { StringKey::EditorAutoSave,         "Auto-Speichern aktivieren" },
    { StringKey::EditorSave,             "Speichern" },
    // ── Migration: vereinheitlichte UI-Strings ──
    { StringKey::SettingsGenFullscreenAnim,  "Vollbild-Animation" },
    { StringKey::SettingsGenAnimSlide,  "Verschieben (seitlich)" },
    { StringKey::SettingsGenAnimFade,  "Überblenden (weicher Zoom)" },
    { StringKey::SettingsGenAudioPlayer,  "Audio-Player" },
    { StringKey::SettingsGenAudioAccentTheme,  "Theme-Akzentfarbe" },
    { StringKey::SettingsGenAudioAccentApple,  "Apple-Blau" },
    { StringKey::SettingsGenRenderBackend,  "Render-Backend" },
    { StringKey::SettingsGenBackendLabel,  "Backend:" },
    { StringKey::SettingsGenBackendAuto,  "Auto" },
    { StringKey::SettingsGenBackendSoftware,  "Software (kein GPU)" },
    { StringKey::SettingsGenActiveBackend,  "Aktuell aktiv: %1  —  Änderungen werden beim nächsten Start wirksam." },
    { StringKey::SettingsGenSoftwareWarning,  "⚠  Software-Renderer aktiv. Möglicherweise wurde beim letzten Start ein inkompatibles Backend erkannt und automatisch zurückgesetzt." },
    { StringKey::SettingsGenVideoInternal,  "Intern (eingebauter Player)" },
    { StringKey::SettingsGenVideoExternal,  "Extern (System-Player)" },
    { StringKey::SettingsGenSaveClose,  "Speichern & Schließen" },
    { StringKey::SettingsGenMonoPlay,  "Mono-Play" },
    { StringKey::SettingsGenMonoPlayLabel,  "Nur eine Wiedergabe gleichzeitig" },
    { StringKey::SettingsGenMonoPlayHint,  "Startet in der geteilten Ansicht eine weitere Audio-/Video-Wiedergabe, wird die bereits laufende automatisch pausiert (nicht gestoppt — die Position bleibt erhalten). Deaktiviert dürfen mehrere Wiedergaben parallel laufen." },
    { StringKey::SettingsViewTileSize,  "Kachelgröße" },
    { StringKey::SettingsViewWidth,  "Breite:" },
    { StringKey::SettingsViewHeight,  "Höhe:" },
    { StringKey::SettingsViewTileArrangement,  "Kachel-Anordnung" },
    { StringKey::SettingsViewAlignLeft,  "Linksbündig" },
    { StringKey::SettingsViewAlignCenter,  "Zentriert" },
    { StringKey::SettingsViewAlignRight,  "Rechtsbündig" },
    { StringKey::SettingsViewAlignManual,  "Manuell (freier Bereich)" },
    { StringKey::SettingsViewArrangementHint,  "Bestimmt, wie Kacheln innerhalb des sichtbaren Bereichs ausgerichtet werden." },
    { StringKey::SettingsViewZoomHint,  "<b>Zoom-Shortcuts:</b><br>Strg + Mausrad → Kachelgröße ändern<br>Strg + + / Strg + − → Kachelgröße stufenweise" },
    { StringKey::SettingsDesignProfileLabel,  "Design-Profil" },
    { StringKey::SettingsDesignCustomHint,  "Wähle das Profil „Custom“, um eigene Farben zu bearbeiten." },
    { StringKey::SettingsDesignTextPrimary,  "Text primär" },
    { StringKey::SettingsDesignTextMuted,  "Text gedämpft" },
    { StringKey::SettingsDesignFrame,  "Rahmen" },
    { StringKey::SettingsDesignBackground,  "Hintergrund" },
    { StringKey::SettingsDesignAccentType,  "Akzent-Typ" },
    { StringKey::SettingsDesignAccentColorLabel,  "Akzentfarbe" },
    { StringKey::SettingsDesignAccentGradEnd,  "Akzent Verlauf-Ende" },
    { StringKey::SettingsDesignGradStartLabel,  "Verlauf Start" },
    { StringKey::SettingsDesignGradEndLabel,  "Verlauf Ende" },
    { StringKey::SettingsDesignGradAngle,  "Verlauf-Winkel" },
    { StringKey::SettingsDesignAngleLabel,  "Winkel" },
    { StringKey::SettingsDesignGlow,  "Glow" },
    { StringKey::SettingsDesignGlowRadiusLabel,  "Glow-Radius" },
    { StringKey::SettingsDesignGlowIntensityLabel,  "Glow-Intensität" },
    { StringKey::SettingsDesignGlowHover,  "Glow beim Überfahren" },
    { StringKey::SettingsDesignCardTile,  "Karte / Kachel" },
    { StringKey::SettingsDesignTileBgLabel,  "Kachel-Hintergrund" },
    { StringKey::SettingsDesignTileColorLabel,  "Kachel-Farbe" },
    { StringKey::SettingsDesignTileGradEndLabel,  "Kachel Verlauf-Ende" },
    { StringKey::SettingsDesignGradInsteadSolid,  "Verlauf statt Einfarbig" },
    { StringKey::SettingsDesignTypeLabel,  "Typ" },
    { StringKey::SettingsDesignBars,  "Leisten" },
    { StringKey::SettingsDesignMenuBar,  "Menüleiste" },
    { StringKey::SettingsDesignToolbar,  "Werkzeugleiste" },
    { StringKey::SettingsDesignFilterBar,  "Filterleiste" },
    { StringKey::SettingsDesignStatusBar,  "Statusleiste" },
    { StringKey::SettingsDesignPdfViewer,  "PDF-Betrachter" },
    { StringKey::SettingsDesignSidebar,  "Seitenleiste" },
    { StringKey::SettingsDesignEditorBgText, "Editor (Text/Code)" },
    { StringKey::SettingsDesignEditorBgHtml, "Editor (HTML)" },
    { StringKey::SettingsDesignScrollbar,  "Scrollleiste" },
    { StringKey::SettingsDesignViewerBg,  "Betrachter-Hintergrund" },
    { StringKey::SettingsDesignThumbBg,  "Thumbnail-Hintergrund" },
    { StringKey::SettingsDesignThemeNameExport,  "Theme-Name & Export" },
    { StringKey::SettingsDesignExportBtn,  "Exportieren…" },
    { StringKey::SettingsDesignImportBtn,  "Importieren…" },
    { StringKey::SettingsDesignApplyBtn,  "Übernehmen" },
    { StringKey::SettingsDesignThemeFileFilter,  "Theme-Dateien (*.json)" },
    { StringKey::SettingsDesignAllFilesFilter,  "Alle Dateien (*)" },
    { StringKey::SettingsConvTagLabel,  "Tag:" },
    { StringKey::SettingsConvTargetCat,  "Ziel-Kategorie:" },
    { StringKey::SettingsConvSubcatLabel,  "Unterkategorie:" },
    { StringKey::SettingsConvCatLabel,  "Kategorie:" },
    { StringKey::SettingsConvModeLabel,  "Richtung:" },
    { StringKey::SettingsConvConvertBtn,  "Umwandeln" },
    { StringKey::SettingsConvTagToSubHint,  "Wandelt einen globalen Tag in eine Unterkategorie um. Der Tag wird danach aus der globalen Liste entfernt." },
    { StringKey::SettingsConvSubToTagHint,  "Wandelt eine Unterkategorie zurück in einen globalen Tag. Alle Dateien der Unterkategorie erhalten diesen Tag." },
    { StringKey::SettingsConvTagToCatHint,  "Wandelt einen globalen Tag in eine eigenständige Hauptkategorie um. Der Tag wird danach aus der globalen Liste entfernt." },
    { StringKey::SettingsConvCatToTagHint,  "Wandelt eine Hauptkategorie in einen globalen Tag um. Alle Dateien der Kategorie erhalten diesen Tag; enthaltene Unterkategorien werden mit entfernt." },
    { StringKey::SettingsConvSubToCatHint,  "Hebt eine Unterkategorie (samt Inhalt) auf die Hauptebene an — sie wird zur eigenständigen Kategorie." },
    { StringKey::SettingsConvCatToSubHint,  "Ordnet eine Hauptkategorie (samt Inhalt) einer anderen Kategorie unter. Das Ziel darf nicht innerhalb der verschobenen Kategorie liegen." },
    { StringKey::SettingsBookBtnAdd,  "+ Ordner hinzufügen" },
    { StringKey::SettingsBookHint,  "Schnellzugriff auf häufig genutzte Ordner." },
    { StringKey::SettingsBookEmpty,  "Noch keine Lesezeichen vorhanden." },
    { StringKey::SettingsBookAddTitle,  "Lesezeichen hinzufügen" },
    { StringKey::SettingsBookEditTitle,  "Lesezeichen bearbeiten" },
    { StringKey::SettingsBookDeleteTitle,  "Lesezeichen löschen" },
    { StringKey::SettingsBookDeleteConfirm,  "Dieses Lesezeichen wirklich entfernen?" },
    { StringKey::SettingsBookFolderPath,  "Ordnerpfad" },
    { StringKey::SettingsBookDisplayName,  "Anzeigename (optional)" },
    { StringKey::SettingsBookChooseFolder,  "Ordner wählen" },
    { StringKey::SettingsCatBtnNew,  "+ Neue Kategorie" },
    { StringKey::SettingsCatHintNew,  "Kategorien und Unterkategorien verwalten. Tags lassen sich Kategorien zuordnen." },
    { StringKey::SettingsCatEmptyNew,  "Noch keine Kategorien vorhanden." },
    { StringKey::SettingsCatColorLabel,  "Farbe:" },
    { StringKey::SettingsCatInheritSub,  "An Unterkategorien vererben" },
    { StringKey::SettingsCatDeleteConfirm,  "Kategorie „%1\" und alle Unterkategorien löschen?" },
    { StringKey::SettingsTagsBtnNew,  "+ Neuer Tag" },
    { StringKey::SettingsTagsHintNew,  "Tags umbenennen, einfärben oder löschen. Änderungen wirken global." },
    { StringKey::SettingsTagsEmpty,  "Noch keine Tags vorhanden." },
    { StringKey::SettingsTagsName,  "Tag-Name" },
    { StringKey::SettingsTagsDeleteConfirm,  "Tag „%1\" wirklich löschen? Er wird aus allen Dateien entfernt." },
    { StringKey::SettingsCatNodeAddSub,  "Unterkategorie…" },
    { StringKey::SettingsCatNodeRename,  "Umbenennen…" },
    { StringKey::SettingsCatNodeSetUniform,  "Einheitsfarbe setzen…" },
    { StringKey::SettingsCatNodeClearUniform,  "Einheitsfarbe entfernen" },
    { StringKey::SettingsCatNodeColorTitle,  "Kategorie-Farbe" },
    { StringKey::SettingsTabViewLayout,  "Ansicht / Layout" },
    { StringKey::SettingsTabEditorShort,  "Editor" },
    { StringKey::SettingsTabConverter,  "Converter" },
    { StringKey::SettingsTabBookmarks,  "Lesezeichen" },
    { StringKey::SettingsClose,  "Schließen" },
    { StringKey::SettingsEditorAutoSaveGroup,  "Automatisches Speichern" },
    { StringKey::SettingsEditorIntervalLabel,  "Intervall:" },
    { StringKey::ColorPickerTitle,  "Farbe wählen" },
    { StringKey::TileSizeHint,  "Ziehe den Eck-Griff der ersten Kachel, um die bevorzugte Kachelgröße einzustellen." },
    { StringKey::MenuTileSize,  "Kachelgröße…" },
    { StringKey::TagPanelEmpty,  "Noch keine Kategorien." },
    { StringKey::TagPanelDeleteTitle,  "Kategorie löschen?" },
    { StringKey::CatNodeRemoveFromCat,  "Aus Kategorie entfernen" },
    { StringKey::FilterNoTagsShort,  "Keine Tags vorhanden" },
    { StringKey::ViewerOpenedExternal,  "Im externen Player geöffnet." },
    { StringKey::ViewerNoRenderer,  "Kein Vorschau-Renderer für diesen Typ." },
    { StringKey::PdfPageIndicator,  "Seite %1 / %2" },
    { StringKey::PdfAudioPanelHeader,  "Audio · Seite %1" },
    { StringKey::PdfNoAudioOnPage,  "Keine Audios auf dieser Seite." },
    { StringKey::PdfAudioItemLabel,  "Audio %1" },

    // ── Batch 2 ──
    { StringKey::FilterModeAnyDesc,  "Mindestens einer der gewählten Tags" },
    { StringKey::FilterModeAllDesc,  "Alle gewählten Tags müssen vorhanden sein" },
    { StringKey::FilterModeExclusiveDesc,  "Ausschließlich die gewählten Tags" },
    { StringKey::FilterModeInclusiveDesc,  "Enthält die gewählten Tags (inklusiv)" },
    { StringKey::FilterSortLabel,  "Sortieren:" },
    { StringKey::FilterSortDesc,  "Absteigend" },
    { StringKey::FilterSortAsc,  "Aufsteigend" },
    { StringKey::FilterTagModeLabel,  "Tag-Filtermodus" },
    { StringKey::FilterActiveSuffix,  " aktiv" },
    { StringKey::FilterShowMediaTypes,  "Medientypen anzeigen" },
    { StringKey::FilterTagsToFilter,  "Tags zum Filtern" },
    { StringKey::ModeGroup,  "Gruppen-Modus" },
    { StringKey::ModeAddToTag,  "Add-to-Tag-Modus" },
    { StringKey::ViewerRandom,  "Zufällig" },
    { StringKey::GalleryNoMedia,  "Keine anzeigbaren Medien in diesem Ordner." },
    { StringKey::GalleryNoFolder,  "Kein Ordner geöffnet — Datei ▸ Ordner öffnen oder hierher ziehen." },
    { StringKey::DateYear,  "Jahr" },
    { StringKey::DateMonth,  "Monat" },
    { StringKey::DateDay,  "Tag" },
    { StringKey::DateHour,  "Stunde" },
    { StringKey::DateMinute,  "Minute" },
    { StringKey::PdfLoadError,  "PDF konnte nicht geladen werden." },
    { StringKey::PdfCollapsePreview,  "Seitenvorschau einklappen" },
    { StringKey::PdfExpandPreview,  "Seitenvorschau ausklappen" },
    { StringKey::PdfHideAudioBar,  "Audioleiste ausblenden" },
    { StringKey::PdfShowAudioBar,  "Audioleiste einblenden" },
    { StringKey::PdfFitPage,  "Ganze Seite" },
    { StringKey::PdfFitWidth,  "Breite" },
    { StringKey::PdfAudioActiveTitle,  "Audio %1 · S. %2" },
    { StringKey::ViewerShowPreview,  "Vorschau anzeigen" },
    { StringKey::ViewerShowSource,   "Quelltext anzeigen" },
    { StringKey::ViewerPreviewCrashed, "Vorschau abgestürzt — über den Button oben zur Quelltext-Ansicht wechseln oder die Datei neu öffnen." },
    { StringKey::FilterAddTagBtn,  "Hinzufügen" },
    { StringKey::FilterAddTagPlaceholder,  "Tag eingeben…" },
    { StringKey::CtxAddTag,  "Tag hinzufügen" },
    { StringKey::CtxAddCategory,  "Kategorie hinzufügen" },
    { StringKey::CtxNoCategories,  "Keine Kategorien vorhanden" },
    { StringKey::OverlayShowTags,  "Tags anzeigen" },
    { StringKey::OverlayShowCategories,  "Kategorien anzeigen" },
    { StringKey::OverlayNoValues,  "— keine —" },

    { StringKey::PanelSectionTags,     "Tags" },
    { StringKey::PanelAddTagTip,       "Neuen Tag erstellen" },
    { StringKey::PanelAddCategoryTip,  "Neue Kategorie erstellen" },
    { StringKey::PanelNoTags,          "Noch keine Tags." },
    { StringKey::FilterTagsCatsLabel,  "Tags & Kategorien" },
    { StringKey::FilterPanelHeader,    "Seitenpanel" },
    { StringKey::FilterTagPanelRow,    "Tag-Panel" },
    { StringKey::FilterCatPanelRow,    "Kategorie-Panel" },

    // ── PDF-Editor (Overlay-Textboxen) ──
    { StringKey::PdfEditToggleTip,         "Bearbeitungsmodus (Overlay)" },
    { StringKey::PdfEditUndoTip,           "Rückgängig" },
    { StringKey::PdfEditRedoTip,           "Wiederholen" },
    { StringKey::PdfEditSnapTip,           "An PDF-Textzeilen ausrichten" },
    { StringKey::PdfEditPanelHeader,       "Text-Eigenschaften" },
    { StringKey::PdfEditNoSelection,       "Textbox auswählen oder per Klick auf die Seite eine neue erstellen." },
    { StringKey::PdfEditFontLabel,         "Schriftart" },
    { StringKey::PdfEditSizeLabel,         "Größe" },
    { StringKey::PdfEditStyleLabel,        "Stil" },
    { StringKey::PdfEditAlignLabel,        "Ausrichtung" },
    { StringKey::PdfEditVAlignLabel,       "Vertikal" },
    { StringKey::PdfEditToolReplace,       "Text ersetzen" },
    { StringKey::CreateFileTypeDocx,     "Word-Dokument (DOCX)" },
    { StringKey::SettingsDocxGroup,      "DOCX-Editor" },
    { StringKey::DocxSaveModeLabel,      "Speicherverhalten" },
    { StringKey::DocxSaveDirect,         "Direkt speichern" },
    { StringKey::DocxSaveDirectHint,     "Schreibt auf die Originaldatei; beim ersten Speichern einer Sitzung entsteht daneben eine .bak-Sicherungskopie." },
    { StringKey::DocxSaveCopy,           "Kopie exportieren" },
    { StringKey::DocxSaveCopyHint,       "Das Original bleibt unangetastet; beim Speichern entsteht daneben <Name>_edited(.n).docx." },
    { StringKey::DocxLoadError,          "DOCX konnte nicht geladen werden" },
    { StringKey::DocxSaveError,          "Speichern fehlgeschlagen" },
    { StringKey::DocxExportedTo,         "Exportiert: %1" },
    { StringKey::DocxTablePlaceholder,   "Tabelle — Bearbeitung folgt in einer späteren Version" },
    { StringKey::DocxPageBreak,          "Seitenumbruch" },
    { StringKey::DocxAlignJustify,       "Blocksatz" },
    { StringKey::DocxLineSpacing,        "Zeilenabstand" },
    { StringKey::DocxSpaceBefore,        "Abstand davor (pt)" },
    { StringKey::DocxSpaceAfter,         "Abstand danach (pt)" },
    { StringKey::DocxBullets,            "Aufzählung" },
    { StringKey::DocxNumbered,           "Nummerierte Liste" },
    { StringKey::DocxSpacingGroup,             "Abstände" },
    { StringKey::DocxListNone,                 "Keine Liste" },
    { StringKey::DocxListType,                 "Listenart" },
    { StringKey::DocxExportPdf,                 "\u2192 PDF" },
    { StringKey::DocxExportPdfTip,             "Als PDF exportieren (Original bleibt erhalten)" },
    { StringKey::DocxPdfExportedTo,            "PDF exportiert: %1" },
    { StringKey::DocxPdfError,                 "PDF-Export fehlgeschlagen" },
    { StringKey::DocxFindPlaceholder,          "Suchen" },
    { StringKey::DocxReplacePlaceholder,       "Ersetzen durch" },
    { StringKey::DocxFindPrev,                 "Vorheriger Treffer" },
    { StringKey::DocxFindNext,                 "Nächster Treffer" },
    { StringKey::DocxReplaceOne,               "Ersetzen" },
    { StringKey::DocxReplaceAll,               "Alle ersetzen" },
    { StringKey::DocxMatchCase,                "Groß-/Kleinschreibung beachten" },
    { StringKey::DocxFindNoMatch,              "Kein Treffer" },
    { StringKey::DocxReplacedCount,            "%1 ersetzt" },
    { StringKey::PdfEditColorLabel,        "Textfarbe" },
    { StringKey::PdfEditHighlightLabel,    "Notiz-Hintergrund" },
    { StringKey::PdfEditCoverLabel,        "Deckfläche" },
    { StringKey::PdfOcrBtn,                 "OCR" },
    { StringKey::PdfOcrTip,                 "Text dieser Seite per OCR erkennen (gescannte PDFs)" },
    { StringKey::PdfOcrBusy,                "OCR läuft …" },
    { StringKey::PdfOcrDone,                "%1 Zeilen per OCR erkannt" },
    { StringKey::PdfOcrNone,                "Kein Text erkannt" },
    { StringKey::PdfChainLink,              "Mit nächster Box verketten" },
    { StringKey::PdfChainUnlink,            "Kette lösen" },
    { StringKey::PdfChainPick,              "Zielbox anklicken …" },
    { StringKey::PdfChainDone,              "Boxen verkettet (Text fließt über)" },
    { StringKey::PdfEditExportVectorBtn,    "→ PDF (Text im Stream)" },
    { StringKey::PdfEditExportVectorTip,    "„Text ersetzen“ verlustfrei in die Textebene schreiben (Datei bleibt vektoriell); sonst automatischer Raster-Export" },
    { StringKey::PdfContentFallbackToast,   "Nicht verlustfrei möglich – Raster-Export verwendet" },
    { StringKey::PdfEditNoHighlight,       "Keine" },
    { StringKey::PdfEditDeleteBtn,         "Textbox löschen" },
    { StringKey::PdfEditAnchoredChip,      "an Textzeile verankert" },
    { StringKey::PdfEditEmptyHint,         "Text eingeben…" },
    { StringKey::PdfEditSaveBtn,           "Speichern" },
    { StringKey::PdfEditSaveTip,           "Änderungen sichern (bleibt editierbar)" },
    { StringKey::PdfEditExportBtn,         "Export" },
    { StringKey::PdfEditExportTip,         "PDF mit eingerechneten Änderungen erzeugen" },
    { StringKey::PdfEditSavedToast,        "Änderungen gespeichert" },
    { StringKey::PdfEditSaveFailedToast,   "Speichern fehlgeschlagen" },
    { StringKey::PdfEditExportDoneToast,   "Exportiert: %1" },
    { StringKey::PdfEditExportFailedToast, "Export fehlgeschlagen: %1" },
    { StringKey::PdfEditExportingToast,    "Exportiere… Seite %1/%2" },
    { StringKey::SettingsPdfEditGroup,     "PDF-Editor" },

    // ── PDF-Editor Runde 2: Post-it-Notizen + Panel-Position ──
    { StringKey::PdfEditNotesToggleTip,    "Notizen ein-/ausblenden (Alt+Q)" },
    { StringKey::PdfEditOpacityLabel,      "Deckkraft" },
    { StringKey::PdfEditPanelPosLabel,     "Position der Text-Eigenschaften" },
    { StringKey::PdfEditPanelPosRight,     "Rechts (Seitenleiste)" },
    { StringKey::PdfEditPanelPosTop,       "Oben (Leiste wie Word)" },

    // ── Datei-Erstellung (FilterBar „Erstellen") ──
    { StringKey::CreateFileBtn,            "Erstellen" },
    { StringKey::CreateFileTitle,          "Neue Datei erstellen" },
    { StringKey::CreateFileNameLabel,      "Dateiname" },
    { StringKey::CreateFileTypePdf,        "Leere PDF" },
    { StringKey::CreateFileTypeHtml,       "Leere HTML-Datei" },
    { StringKey::CreateFileTypeTxt,        "Leere Textdatei" },
    { StringKey::CreateFileDone,           "Erstellt: %1" },
    { StringKey::CreateFileFailed,         "Datei konnte nicht erstellt werden." },

    // ── Galerie-Kontextmenü: Datei löschen ──
    { StringKey::CtxDeleteFile,            "Datei löschen…" },
    { StringKey::DeleteMediaTitle,         "Datei löschen" },
    { StringKey::DeleteMediaText,          "„%1“ wird in den Papierkorb verschoben." },
    { StringKey::DeleteMediaConfirm,       "Löschen" },

    // ── Live-Transliteration ──
    { StringKey::TranslitTip,              "Transliteration (Latein → Arabisch/Japanisch)" },
    { StringKey::TranslitOff,              "Aus" },
    { StringKey::TranslitArabic,           "Arabisch (mit Harakat)" },
    { StringKey::TranslitHiragana,         "Japanisch – Hiragana" },
    { StringKey::TranslitKatakana,         "Japanisch – Katakana" },
    { StringKey::SettingsTranslitGroup,    "Transliteration beim Schreiben" },
    { StringKey::TranslitSchemeLabel,      "Schema" },
    { StringKey::TranslitKeyPlaceholder,   "Eingabe (Latein)" },
    { StringKey::TranslitValuePlaceholder, "Ausgabe (Zielschrift)" },
    { StringKey::TranslitAddBtn,           "Hinzufügen" },
    { StringKey::TranslitResetBtn,         "Auf Standard zurücksetzen" },
    { StringKey::TranslitHint,             "Beim Schreiben von Text (TXT, HTML, PDF-Notizen) wird die lateinische Eingabe live in die Zielschrift umgesetzt – aber erst, sobald eindeutig ist, welches Zeichen gemeint ist (z. B. wird „a“ erst umgewandelt, wenn feststeht, dass kein längeres Kürzel wie „aa“ folgt). Die Zuordnungen unten lassen sich frei bearbeiten, ergänzen und löschen." },
    { StringKey::SplitAddFile,             "Datei hinzufügen" },
    { StringKey::SplitMaxReached,          "Maximal 4 Dateien gleichzeitig geöffnet — bitte zuerst eine schließen." },
    { StringKey::SplitPickPrompt,          "Datei anklicken, um sie zur geteilten Ansicht hinzuzufügen" },
    { StringKey::SplitCancel,              "Abbrechen" },

    // ── Bild-Editor ───────────────────────────────────────────────────────────
    { StringKey::ImageEditToggle,          "Bild bearbeiten" },
    { StringKey::ImageFitWindow,           "An Fenster anpassen" },
    { StringKey::ImageActualSize,          "100 %" },
    { StringKey::ImageZoomIn,              "Vergrößern" },
    { StringKey::ImageZoomOut,             "Verkleinern" },
    { StringKey::ImageLoadError,           "Bild konnte nicht geladen werden." },
    { StringKey::ImageEditPanelTitle,      "Bild-Editor" },
    { StringKey::ImageEditToolsLabel,      "Werkzeuge" },
    { StringKey::ImageEditToolSelect,      "Auswählen / Verschieben" },
    { StringKey::ImageEditToolText,        "Textnotiz" },
    { StringKey::ImageEditToolPen,         "Stift (Freihand)" },
    { StringKey::ImageEditToolArrow,       "Pfeil" },
    { StringKey::ImageEditToolRect,        "Rechteck" },
    { StringKey::ImageEditToolEllipse,     "Ellipse" },
    { StringKey::ImageEditPickHint,        "Werkzeug wählen oder eine Annotation anklicken." },
    { StringKey::ImageEditEmptyHint,       "Text eingeben…" },
    { StringKey::ImageEditStrokeLabel,     "Linienfarbe" },
    { StringKey::ImageEditWidthLabel,      "Linienbreite" },
    { StringKey::ImageEditFillLabel,       "Füllung" },
    { StringKey::ImageEditCopyBtn,         "Kopieren" },
    { StringKey::ImageEditPasteBtn,        "Einfügen" },
    { StringKey::ImageEditDocSection,      "Dokument" },

    // ── PDF-Seiten-Extraktion ────────────────────────────────────────────────
    { StringKey::CtxExtractPage,           "Seite extrahieren" },
    { StringKey::CtxExtractPages,          "Mehrere Seiten extrahieren…" },
    { StringKey::ExtractNameTitle,         "Neue PDF benennen" },
    { StringKey::ExtractNameLabel,         "Dateiname" },
    { StringKey::ExtractCreateBtn,         "Extrahieren" },
    { StringKey::ExtractDialogTitle,       "Seiten extrahieren" },
    { StringKey::ExtractGlobalTitle,       "PDF-Seiten aus Ordner extrahieren" },
    { StringKey::ExtractHintCtrl,          "Klicken wählt Seiten aus und ab. Strg gedrückt halten und mit der Maus über eine Seite fahren zeigt eine große Vorschau." },
    { StringKey::ExtractSelectedCount,     "%1 Seiten ausgewählt" },
    { StringKey::ExtractNoPdfs,            "In diesem Ordner gibt es keine PDF-Dateien." },
    { StringKey::FilterExtractBtn,         "Extrahieren" },
    { StringKey::ExtractOkToast,           "PDF erstellt: %1" },
    { StringKey::ExtractFailToast,         "Extraktion fehlgeschlagen." },
    { StringKey::ExtractProgressToast,     "Extrahiere Seite %1/%2" },
    { StringKey::ExtractPageShort,         "S. %1" },
    { StringKey::SettingsViewExtractStyle,     "PDF-Extraktion: Auswahl-Darstellung" },
    { StringKey::SettingsViewExtractStyleHint, "Wie ausgewählte Seiten im Extraktionsdialog hervorgehoben werden." },
    { StringKey::ExtractStyleFrame,        "Rahmen" },
    { StringKey::ExtractStyleOverlay,      "Überlagerung" },
    { StringKey::SettingsPdfPageEditLabel,   "Seiten hinzufügen/entfernen" },
    { StringKey::SettingsPdfPageEditHint,    "Im PDF-Editiermodus fügt die „+\"-Linie unter einer Seite eine leere A4-Seite ein; Rechtsklick auf eine Seite bietet „Seite entfernen\". Strg+Z macht beides rückgängig." },
    { StringKey::PdfPageEditNonDestructive,  "Nicht-destruktiv (Änderungen wirken beim Export)" },
    { StringKey::PdfPageEditDestructiveMode, "Destruktiv (Original-PDF sofort ändern)" },
    { StringKey::PdfAddPageTip,              "Leere A4-Seite hier einfügen" },
    { StringKey::PdfRemovePage,              "Seite entfernen" },
    { StringKey::SettingsGenShortcuts,       "Tastenkürzel" },
    { StringKey::ShortcutCtxGallery,         "Galerie" },
    { StringKey::ShortcutCtxViewer,          "Medienansicht" },
    { StringKey::ShortcutCtxPdf,             "PDF-Editor" },
    { StringKey::ShortcutCtxImage,           "Bild-Editor" },
    { StringKey::ShortcutCtxDocx,            "DOCX-Editor" },
    { StringKey::ShortcutCtxText,            "Texteditor" },
    { StringKey::SettingsViewExtractLayout,     "Layout des Extraktionsdialogs" },
    { StringKey::SettingsViewExtractLayoutHint, "Werkbank: PDF-Liste, Seitenraster und Auswahlleiste mit frei sortierbarer Reihenfolge. Kompakt: schlichtes Einzelraster." },
    { StringKey::ExtractLayoutWorkbench,        "Werkbank (Standard)" },
    { StringKey::ExtractLayoutCompact,          "Kompakt (minimalistisch)" },
    { StringKey::ExtractWorkPdfs,               "PDFs" },
    { StringKey::ExtractWorkPages,              "Seiten" },
    { StringKey::ExtractWorkOrder,              "Auswahl · Reihenfolge = Ausgabe" },
    { StringKey::ExtractWorkHint,               "Seite anklicken oder in die Leiste ziehen · in der Leiste ziehen zum Umsortieren · aus der Leiste ziehen zum Entfernen" },
    { StringKey::ExtractWorkDropHint,           "Seiten oder ganze PDFs hierher ziehen" },

};

// ─────────────────────────────────────────────────────────────────────────────
// English strings
// ─────────────────────────────────────────────────────────────────────────────
static const QMap<StringKey, QString> s_en = {
    { StringKey::MenuFile,              "File" },
    { StringKey::MenuView,              "View" },
    { StringKey::MenuSettings,          "Settings" },
    { StringKey::MenuOpenFolder,        "Open Folder…" },
    { StringKey::MenuRefresh,           "Reload (R)" },
    { StringKey::MenuQuit,              "Quit" },
    { StringKey::MenuToggleOptions,     "Toggle Options (Alt+S)" },
    { StringKey::MenuSettingsItem,      "Settings…" },
    { StringKey::MenuLanguage,          "Language" },
    { StringKey::MenuVideoPlayback,     "Video Playback" },
    { StringKey::MenuVideoNative,       "Native" },
    { StringKey::MenuVideoExternal,     "External Player" },

    { StringKey::FilterAudio,           "Audio" },
    { StringKey::FilterMedia,           "Media" },
    { StringKey::FilterDate,            "Date" },
    { StringKey::FilterName,            "Name" },
    { StringKey::FilterTags,            "Tags" },
    { StringKey::FilterFileSize,        "File Size" },
    { StringKey::FilterTagModeAnd,      "AND" },
    { StringKey::FilterTagModeOr,       "OR" },
    { StringKey::FilterTagModeNur,      "ONLY" },
    { StringKey::FilterTagModeInklusiv, "INCLUSIVE" },


    { StringKey::SettingsTitle,         "Settings" },
    { StringKey::SettingsTabGeneral,    "General" },
    { StringKey::SettingsTabDesign,     "Design" },
    { StringKey::SettingsLanguageLabel, "Language:" },
    { StringKey::SettingsOk,            "OK" },
    { StringKey::SettingsCancel,        "Cancel" },
    { StringKey::SettingsTagDelete,     "Delete tag" },

    { StringKey::MetaTitle,         "Edit Date" },
    { StringKey::MetaReset,         "Reset" },

    { StringKey::TagBarPlaceholder,     "Add tag…" },
    { StringKey::TagBarDropdownHeader,  "Add tag" },

    { StringKey::CatPanelAddCategory,   "New Category" },
    { StringKey::CatPanelNewSubcategory,"New Subcategory" },
    { StringKey::CatPanelRename,        "Rename" },
    { StringKey::CatPanelDelete,        "Delete Category" },
    { StringKey::CatPanelSetColor,      "Set uniform color" },
    { StringKey::CatPanelNewTag,        "New tag" },


    { StringKey::FilterCatNewName,      "New name:" },
    { StringKey::FilterTagRenamePrompt, "Rename Tag" },

    { StringKey::SettingsTabCategories,  "Categories" },
    { StringKey::SettingsCatNewLabel,    "Name:" },
    { StringKey::SettingsCatRenameTitle, "Rename Category" },
    { StringKey::SettingsTagColorTitle,  "Tag Color" },

    { StringKey::SettingsDesignBaseColors,      "Base Colors" },
    { StringKey::SettingsDesignBgGradient,      "Background Gradient" },
    { StringKey::SettingsDesignAccent,          "Accent" },
    { StringKey::SettingsDesignAccentSolid,     "Solid" },
    { StringKey::SettingsDesignAccentGradient,  "Gradient" },
    { StringKey::SettingsDesignTileTransparent, "Transparent" },
    { StringKey::SettingsDesignExportTitle,     "Export Theme" },
    { StringKey::SettingsDesignImportTitle,     "Import Theme" },

    // Converter
    { StringKey::ConverterTagToSubcat,    "Tag → Subcategory" },
    { StringKey::ConverterSubcatToTag,    "Subcategory → Tag" },
    { StringKey::ConverterTagToCat,       "Tag → Category" },
    { StringKey::ConverterCatToTag,       "Category → Tag" },
    { StringKey::ConverterSubcatToCat,    "Subcategory → Category" },
    { StringKey::ConverterCatToSubcat,    "Category → Subcategory" },

    // Design – PDF viewer / sidebar / button colors

    // Uniform-color UI

    // Main-window chrome bars

    // Converter – localized hint texts

    // PdfViewer – localized texts

    // Saved Folders / Bookmarks
    { StringKey::MenuBookmarks,          "Folders" },
    { StringKey::MenuBookmarksEmpty,     "(no saved folders)" },
    { StringKey::BookmarkAdd,            "Add Folder" },
    { StringKey::BookmarkEdit,           "Edit" },
    { StringKey::BookmarkDelete,         "Delete" },
    { StringKey::BookmarkPathLabel,      "Path:" },
    { StringKey::BookmarkBrowse,         "Browse…" },

    { StringKey::EditorAutoSave,         "Enable Auto-Save" },
    { StringKey::EditorSave,             "Save" },
    // ── Migration: vereinheitlichte UI-Strings ──
    { StringKey::SettingsGenFullscreenAnim,  "Fullscreen Animation" },
    { StringKey::SettingsGenAnimSlide,  "Slide (horizontal)" },
    { StringKey::SettingsGenAnimFade,  "Fade (soft zoom)" },
    { StringKey::SettingsGenAudioPlayer,  "Audio Player" },
    { StringKey::SettingsGenAudioAccentTheme,  "Theme accent color" },
    { StringKey::SettingsGenAudioAccentApple,  "Apple blue" },
    { StringKey::SettingsGenRenderBackend,  "Render Backend" },
    { StringKey::SettingsGenBackendLabel,  "Backend:" },
    { StringKey::SettingsGenBackendAuto,  "Auto" },
    { StringKey::SettingsGenBackendSoftware,  "Software (no GPU)" },
    { StringKey::SettingsGenActiveBackend,  "Currently active: %1  —  changes take effect on next start." },
    { StringKey::SettingsGenSoftwareWarning,  "⚠  Software renderer active. An incompatible backend may have been detected on the last start and reset automatically." },
    { StringKey::SettingsGenVideoInternal,  "Internal (built-in player)" },
    { StringKey::SettingsGenVideoExternal,  "External (system player)" },
    { StringKey::SettingsGenSaveClose,  "Save & Close" },
    { StringKey::SettingsGenMonoPlay,  "Mono-Play" },
    { StringKey::SettingsGenMonoPlayLabel,  "Only one playback at a time" },
    { StringKey::SettingsGenMonoPlayHint,  "When another audio/video playback is started in the split view, the one already playing is paused automatically (not stopped — its position is kept). When disabled, multiple playbacks may run in parallel." },
    { StringKey::SettingsViewTileSize,  "Tile Size" },
    { StringKey::SettingsViewWidth,  "Width:" },
    { StringKey::SettingsViewHeight,  "Height:" },
    { StringKey::SettingsViewTileArrangement,  "Tile Arrangement" },
    { StringKey::SettingsViewAlignLeft,  "Left-aligned" },
    { StringKey::SettingsViewAlignCenter,  "Centered" },
    { StringKey::SettingsViewAlignRight,  "Right-aligned" },
    { StringKey::SettingsViewAlignManual,  "Manual (free area)" },
    { StringKey::SettingsViewArrangementHint,  "Determines how tiles are aligned within the visible area." },
    { StringKey::SettingsViewZoomHint,  "<b>Zoom shortcuts:</b><br>Ctrl + mouse wheel → change tile size<br>Ctrl + + / Ctrl + − → tile size stepwise" },
    { StringKey::SettingsDesignProfileLabel,  "Design Profile" },
    { StringKey::SettingsDesignCustomHint,  "Select the \"Custom\" profile to edit your own colors." },
    { StringKey::SettingsDesignTextPrimary,  "Text primary" },
    { StringKey::SettingsDesignTextMuted,  "Text muted" },
    { StringKey::SettingsDesignFrame,  "Border" },
    { StringKey::SettingsDesignBackground,  "Background" },
    { StringKey::SettingsDesignAccentType,  "Accent type" },
    { StringKey::SettingsDesignAccentColorLabel,  "Accent color" },
    { StringKey::SettingsDesignAccentGradEnd,  "Accent gradient end" },
    { StringKey::SettingsDesignGradStartLabel,  "Gradient start" },
    { StringKey::SettingsDesignGradEndLabel,  "Gradient end" },
    { StringKey::SettingsDesignGradAngle,  "Gradient angle" },
    { StringKey::SettingsDesignAngleLabel,  "Angle" },
    { StringKey::SettingsDesignGlow,  "Glow" },
    { StringKey::SettingsDesignGlowRadiusLabel,  "Glow radius" },
    { StringKey::SettingsDesignGlowIntensityLabel,  "Glow intensity" },
    { StringKey::SettingsDesignGlowHover,  "Glow on hover" },
    { StringKey::SettingsDesignCardTile,  "Card / Tile" },
    { StringKey::SettingsDesignTileBgLabel,  "Tile background" },
    { StringKey::SettingsDesignTileColorLabel,  "Tile color" },
    { StringKey::SettingsDesignTileGradEndLabel,  "Tile gradient end" },
    { StringKey::SettingsDesignGradInsteadSolid,  "Gradient instead of solid" },
    { StringKey::SettingsDesignTypeLabel,  "Type" },
    { StringKey::SettingsDesignBars,  "Bars" },
    { StringKey::SettingsDesignMenuBar,  "Menu bar" },
    { StringKey::SettingsDesignToolbar,  "Toolbar" },
    { StringKey::SettingsDesignFilterBar,  "Filter bar" },
    { StringKey::SettingsDesignStatusBar,  "Status bar" },
    { StringKey::SettingsDesignPdfViewer,  "PDF Viewer" },
    { StringKey::SettingsDesignSidebar,  "Sidebar" },
    { StringKey::SettingsDesignEditorBgText, "Editor (text/code)" },
    { StringKey::SettingsDesignEditorBgHtml, "Editor (HTML)" },
    { StringKey::SettingsDesignScrollbar,  "Scrollbar" },
    { StringKey::SettingsDesignViewerBg,  "Viewer background" },
    { StringKey::SettingsDesignThumbBg,  "Thumbnail background" },
    { StringKey::SettingsDesignThemeNameExport,  "Theme name & export" },
    { StringKey::SettingsDesignExportBtn,  "Export…" },
    { StringKey::SettingsDesignImportBtn,  "Import…" },
    { StringKey::SettingsDesignApplyBtn,  "Apply" },
    { StringKey::SettingsDesignThemeFileFilter,  "Theme files (*.json)" },
    { StringKey::SettingsDesignAllFilesFilter,  "All files (*)" },
    { StringKey::SettingsConvTagLabel,  "Tag:" },
    { StringKey::SettingsConvTargetCat,  "Target category:" },
    { StringKey::SettingsConvSubcatLabel,  "Subcategory:" },
    { StringKey::SettingsConvCatLabel,  "Category:" },
    { StringKey::SettingsConvModeLabel,  "Direction:" },
    { StringKey::SettingsConvConvertBtn,  "Convert" },
    { StringKey::SettingsConvTagToSubHint,  "Converts a global tag into a subcategory. The tag is then removed from the global list." },
    { StringKey::SettingsConvSubToTagHint,  "Converts a subcategory back into a global tag. All files of the subcategory receive this tag." },
    { StringKey::SettingsConvTagToCatHint,  "Converts a global tag into a standalone top-level category. The tag is then removed from the global list." },
    { StringKey::SettingsConvCatToTagHint,  "Converts a top-level category into a global tag. All files of the category receive this tag; contained subcategories are removed as well." },
    { StringKey::SettingsConvSubToCatHint,  "Promotes a subcategory (including its contents) to the top level — it becomes a standalone category." },
    { StringKey::SettingsConvCatToSubHint,  "Places a top-level category (including its contents) under another category. The target must not lie inside the moved category." },
    { StringKey::SettingsBookBtnAdd,  "+ Add Folder" },
    { StringKey::SettingsBookHint,  "Quick access to frequently used folders." },
    { StringKey::SettingsBookEmpty,  "No saved folders yet." },
    { StringKey::SettingsBookAddTitle,  "Add Saved Folder" },
    { StringKey::SettingsBookEditTitle,  "Edit Saved Folder" },
    { StringKey::SettingsBookDeleteTitle,  "Delete Saved Folder" },
    { StringKey::SettingsBookDeleteConfirm,  "Really remove this saved folder?" },
    { StringKey::SettingsBookFolderPath,  "Folder path" },
    { StringKey::SettingsBookDisplayName,  "Display name (optional)" },
    { StringKey::SettingsBookChooseFolder,  "Choose Folder" },
    { StringKey::SettingsCatBtnNew,  "+ New Category" },
    { StringKey::SettingsCatHintNew,  "Manage categories and subcategories. Tags can be assigned to categories." },
    { StringKey::SettingsCatEmptyNew,  "No categories yet." },
    { StringKey::SettingsCatColorLabel,  "Color:" },
    { StringKey::SettingsCatInheritSub,  "Inherit to subcategories" },
    { StringKey::SettingsCatDeleteConfirm,  "Delete category \"%1\" and all subcategories?" },
    { StringKey::SettingsTagsBtnNew,  "+ New Tag" },
    { StringKey::SettingsTagsHintNew,  "Rename, recolor or delete tags. Changes apply globally." },
    { StringKey::SettingsTagsEmpty,  "No tags yet." },
    { StringKey::SettingsTagsName,  "Tag name" },
    { StringKey::SettingsTagsDeleteConfirm,  "Really delete tag \"%1\"? It will be removed from all files." },
    { StringKey::SettingsCatNodeAddSub,  "Subcategory…" },
    { StringKey::SettingsCatNodeRename,  "Rename…" },
    { StringKey::SettingsCatNodeSetUniform,  "Set uniform color…" },
    { StringKey::SettingsCatNodeClearUniform,  "Remove uniform color" },
    { StringKey::SettingsCatNodeColorTitle,  "Category Color" },
    { StringKey::SettingsTabViewLayout,  "View / Layout" },
    { StringKey::SettingsTabEditorShort,  "Editor" },
    { StringKey::SettingsTabConverter,  "Converter" },
    { StringKey::SettingsTabBookmarks,  "Saved Folders" },
    { StringKey::SettingsClose,  "Close" },
    { StringKey::SettingsEditorAutoSaveGroup,  "Automatic Saving" },
    { StringKey::SettingsEditorIntervalLabel,  "Interval:" },
    { StringKey::ColorPickerTitle,  "Choose Color" },
    { StringKey::TileSizeHint,  "Drag the corner handle of the first tile to set the preferred tile size." },
    { StringKey::MenuTileSize,  "Tile Size…" },
    { StringKey::TagPanelEmpty,  "No categories yet." },
    { StringKey::TagPanelDeleteTitle,  "Delete category?" },
    { StringKey::CatNodeRemoveFromCat,  "Remove from category" },
    { StringKey::FilterNoTagsShort,  "No tags available" },
    { StringKey::ViewerOpenedExternal,  "Opened in external player." },
    { StringKey::ViewerNoRenderer,  "No preview renderer for this type." },
    { StringKey::PdfPageIndicator,  "Page %1 / %2" },
    { StringKey::PdfAudioPanelHeader,  "Audio · Page %1" },
    { StringKey::PdfNoAudioOnPage,  "No audio on this page." },
    { StringKey::PdfAudioItemLabel,  "Audio %1" },

    // ── Batch 2 ──
    { StringKey::FilterModeAnyDesc,  "At least one of the selected tags" },
    { StringKey::FilterModeAllDesc,  "All selected tags must be present" },
    { StringKey::FilterModeExclusiveDesc,  "Exclusively the selected tags" },
    { StringKey::FilterModeInclusiveDesc,  "Contains the selected tags (inclusive)" },
    { StringKey::FilterSortLabel,  "Sort:" },
    { StringKey::FilterSortDesc,  "Descending" },
    { StringKey::FilterSortAsc,  "Ascending" },
    { StringKey::FilterTagModeLabel,  "Tag filter mode" },
    { StringKey::FilterActiveSuffix,  " active" },
    { StringKey::FilterShowMediaTypes,  "Show media types" },
    { StringKey::FilterTagsToFilter,  "Tags to filter" },
    { StringKey::ModeGroup,  "Group mode" },
    { StringKey::ModeAddToTag,  "Add-to-tag mode" },
    { StringKey::ViewerRandom,  "Random" },
    { StringKey::GalleryNoMedia,  "No displayable media in this folder." },
    { StringKey::GalleryNoFolder,  "No folder open — File ▸ Open folder or drag here." },
    { StringKey::DateYear,  "Year" },
    { StringKey::DateMonth,  "Month" },
    { StringKey::DateDay,  "Day" },
    { StringKey::DateHour,  "Hour" },
    { StringKey::DateMinute,  "Minute" },
    { StringKey::PdfLoadError,  "PDF could not be loaded." },
    { StringKey::PdfCollapsePreview,  "Collapse page preview" },
    { StringKey::PdfExpandPreview,  "Expand page preview" },
    { StringKey::PdfHideAudioBar,  "Hide audio bar" },
    { StringKey::PdfShowAudioBar,  "Show audio bar" },
    { StringKey::PdfFitPage,  "Whole page" },
    { StringKey::PdfFitWidth,  "Width" },
    { StringKey::PdfAudioActiveTitle,  "Audio %1 · p. %2" },
    { StringKey::ViewerShowPreview,  "Show preview" },
    { StringKey::ViewerShowSource,   "Show source" },
    { StringKey::ViewerPreviewCrashed, "Preview crashed — switch to source with the button above, or reopen the file." },
    { StringKey::FilterAddTagBtn,  "Add" },
    { StringKey::FilterAddTagPlaceholder,  "Enter tag…" },
    { StringKey::CtxAddTag,  "Add tag" },
    { StringKey::CtxAddCategory,  "Add category" },
    { StringKey::CtxNoCategories,  "No categories available" },
    { StringKey::OverlayShowTags,  "Show tags" },
    { StringKey::OverlayShowCategories,  "Show categories" },
    { StringKey::OverlayNoValues,  "— none —" },

    { StringKey::PanelSectionTags,     "Tags" },
    { StringKey::PanelAddTagTip,       "Create new tag" },
    { StringKey::PanelAddCategoryTip,  "Create new category" },
    { StringKey::PanelNoTags,          "No tags yet." },
    { StringKey::FilterTagsCatsLabel,  "Tags & Categories" },
    { StringKey::FilterPanelHeader,    "Side panel" },
    { StringKey::FilterTagPanelRow,    "Tag panel" },
    { StringKey::FilterCatPanelRow,    "Category panel" },

    // ── PDF editor (overlay text boxes) ──
    { StringKey::PdfEditToggleTip,         "Edit mode (overlay)" },
    { StringKey::PdfEditUndoTip,           "Undo" },
    { StringKey::PdfEditRedoTip,           "Redo" },
    { StringKey::PdfEditSnapTip,           "Snap to PDF text lines" },
    { StringKey::PdfEditPanelHeader,       "Text properties" },
    { StringKey::PdfEditNoSelection,       "Select a text box or click the page to create one." },
    { StringKey::PdfEditFontLabel,         "Font" },
    { StringKey::PdfEditSizeLabel,         "Size" },
    { StringKey::PdfEditStyleLabel,        "Style" },
    { StringKey::PdfEditAlignLabel,        "Alignment" },
    { StringKey::PdfEditVAlignLabel,       "Vertical" },
    { StringKey::PdfEditToolReplace,       "Replace text" },
    { StringKey::CreateFileTypeDocx,     "Word document (DOCX)" },
    { StringKey::SettingsDocxGroup,      "DOCX Editor" },
    { StringKey::DocxSaveModeLabel,      "Save behavior" },
    { StringKey::DocxSaveDirect,         "Save directly" },
    { StringKey::DocxSaveDirectHint,     "Writes to the original file; the first save of a session creates a .bak backup copy next to it." },
    { StringKey::DocxSaveCopy,           "Export a copy" },
    { StringKey::DocxSaveCopyHint,       "The original stays untouched; saving creates <Name>_edited(.n).docx next to it." },
    { StringKey::DocxLoadError,          "Could not load DOCX" },
    { StringKey::DocxSaveError,          "Saving failed" },
    { StringKey::DocxExportedTo,         "Exported: %1" },
    { StringKey::DocxTablePlaceholder,   "Table — editing coming in a later version" },
    { StringKey::DocxPageBreak,          "Page break" },
    { StringKey::DocxAlignJustify,       "Justify" },
    { StringKey::DocxLineSpacing,        "Line spacing" },
    { StringKey::DocxSpaceBefore,        "Space before (pt)" },
    { StringKey::DocxSpaceAfter,         "Space after (pt)" },
    { StringKey::DocxBullets,            "Bulleted list" },
    { StringKey::DocxNumbered,           "Numbered list" },
    { StringKey::DocxSpacingGroup,             "Spacing" },
    { StringKey::DocxListNone,                 "No list" },
    { StringKey::DocxListType,                 "List type" },
    { StringKey::DocxExportPdf,                 "\u2192 PDF" },
    { StringKey::DocxExportPdfTip,             "Export as PDF (keeps the original)" },
    { StringKey::DocxPdfExportedTo,            "Exported PDF: %1" },
    { StringKey::DocxPdfError,                 "PDF export failed" },
    { StringKey::DocxFindPlaceholder,          "Find" },
    { StringKey::DocxReplacePlaceholder,       "Replace with" },
    { StringKey::DocxFindPrev,                 "Previous match" },
    { StringKey::DocxFindNext,                 "Next match" },
    { StringKey::DocxReplaceOne,               "Replace" },
    { StringKey::DocxReplaceAll,               "Replace all" },
    { StringKey::DocxMatchCase,                "Match case" },
    { StringKey::DocxFindNoMatch,              "No match" },
    { StringKey::DocxReplacedCount,            "%1 replaced" },
    { StringKey::PdfEditColorLabel,        "Text color" },
    { StringKey::PdfEditHighlightLabel,    "Note background" },
    { StringKey::PdfEditCoverLabel,        "Cover" },
    { StringKey::PdfOcrBtn,                 "OCR" },
    { StringKey::PdfOcrTip,                 "Recognize this page's text via OCR (scanned PDFs)" },
    { StringKey::PdfOcrBusy,                "OCR running …" },
    { StringKey::PdfOcrDone,                "%1 lines recognized via OCR" },
    { StringKey::PdfOcrNone,                "No text recognized" },
    { StringKey::PdfChainLink,              "Link to next box" },
    { StringKey::PdfChainUnlink,            "Unlink" },
    { StringKey::PdfChainPick,              "Click the target box …" },
    { StringKey::PdfChainDone,              "Boxes linked (text overflows)" },
    { StringKey::PdfEditExportVectorBtn,    "→ PDF (edit text in stream)" },
    { StringKey::PdfEditExportVectorTip,    "Write “Replace text” losslessly into the text layer (keeps the file vector); otherwise falls back to raster export" },
    { StringKey::PdfContentFallbackToast,   "Lossless edit not possible – used raster export" },
    { StringKey::PdfEditNoHighlight,       "None" },
    { StringKey::PdfEditDeleteBtn,         "Delete text box" },
    { StringKey::PdfEditAnchoredChip,      "anchored to text line" },
    { StringKey::PdfEditEmptyHint,         "Enter text…" },
    { StringKey::PdfEditSaveBtn,           "Save" },
    { StringKey::PdfEditSaveTip,           "Save changes (stays editable)" },
    { StringKey::PdfEditExportBtn,         "Export" },
    { StringKey::PdfEditExportTip,         "Render changes into a new PDF" },
    { StringKey::PdfEditSavedToast,        "Changes saved" },
    { StringKey::PdfEditSaveFailedToast,   "Saving failed" },
    { StringKey::PdfEditExportDoneToast,   "Exported: %1" },
    { StringKey::PdfEditExportFailedToast, "Export failed: %1" },
    { StringKey::PdfEditExportingToast,    "Exporting… page %1/%2" },
    { StringKey::SettingsPdfEditGroup,     "PDF editor" },

    // ── PDF editor round 2: sticky notes + panel position ──
    { StringKey::PdfEditNotesToggleTip,    "Show/hide notes (Alt+Q)" },
    { StringKey::PdfEditOpacityLabel,      "Opacity" },
    { StringKey::PdfEditPanelPosLabel,     "Text properties position" },
    { StringKey::PdfEditPanelPosRight,     "Right (side panel)" },
    { StringKey::PdfEditPanelPosTop,       "Top (Word-style bar)" },

    // ── File creation (filter bar "Create") ──
    { StringKey::CreateFileBtn,            "Create" },
    { StringKey::CreateFileTitle,          "Create new file" },
    { StringKey::CreateFileNameLabel,      "File name" },
    { StringKey::CreateFileTypePdf,        "Empty PDF" },
    { StringKey::CreateFileTypeHtml,       "Empty HTML file" },
    { StringKey::CreateFileTypeTxt,        "Empty text file" },
    { StringKey::CreateFileDone,           "Created: %1" },
    { StringKey::CreateFileFailed,         "Could not create file." },

    // ── Gallery context menu: delete file ──
    { StringKey::CtxDeleteFile,            "Delete file…" },
    { StringKey::DeleteMediaTitle,         "Delete file" },
    { StringKey::DeleteMediaText,          "“%1” will be moved to the trash." },
    { StringKey::DeleteMediaConfirm,       "Delete" },

    // ── Live transliteration ──
    { StringKey::TranslitTip,              "Transliteration (Latin → Arabic/Japanese)" },
    { StringKey::TranslitOff,              "Off" },
    { StringKey::TranslitArabic,           "Arabic (with harakat)" },
    { StringKey::TranslitHiragana,         "Japanese – Hiragana" },
    { StringKey::TranslitKatakana,         "Japanese – Katakana" },
    { StringKey::SettingsTranslitGroup,    "Transliteration while typing" },
    { StringKey::TranslitSchemeLabel,      "Scheme" },
    { StringKey::TranslitKeyPlaceholder,   "Input (Latin)" },
    { StringKey::TranslitValuePlaceholder, "Output (target script)" },
    { StringKey::TranslitAddBtn,           "Add" },
    { StringKey::TranslitResetBtn,         "Reset to defaults" },
    { StringKey::TranslitHint,             "When writing text (TXT, HTML, PDF notes) your Latin input is converted live into the target script — but only once it is unambiguous which character you mean (e.g. “a” is only converted once it is clear no longer sequence such as “aa” follows). The mappings below can be edited, extended and removed freely." },
    { StringKey::SplitAddFile,             "Add file" },
    { StringKey::SplitMaxReached,          "A maximum of 4 files can be open at once — please close one first." },
    { StringKey::SplitPickPrompt,          "Click a file to add it to the split view" },
    { StringKey::SplitCancel,              "Cancel" },

    // ── Image editor ──────────────────────────────────────────────────────────
    { StringKey::ImageEditToggle,          "Edit image" },
    { StringKey::ImageFitWindow,           "Fit to window" },
    { StringKey::ImageActualSize,          "100%" },
    { StringKey::ImageZoomIn,              "Zoom in" },
    { StringKey::ImageZoomOut,             "Zoom out" },
    { StringKey::ImageLoadError,           "Could not load image." },
    { StringKey::ImageEditPanelTitle,      "Image editor" },
    { StringKey::ImageEditToolsLabel,      "Tools" },
    { StringKey::ImageEditToolSelect,      "Select / move" },
    { StringKey::ImageEditToolText,        "Text note" },
    { StringKey::ImageEditToolPen,         "Pen (freehand)" },
    { StringKey::ImageEditToolArrow,       "Arrow" },
    { StringKey::ImageEditToolRect,        "Rectangle" },
    { StringKey::ImageEditToolEllipse,     "Ellipse" },
    { StringKey::ImageEditPickHint,        "Pick a tool or click an annotation." },
    { StringKey::ImageEditEmptyHint,       "Enter text…" },
    { StringKey::ImageEditStrokeLabel,     "Line color" },
    { StringKey::ImageEditWidthLabel,      "Line width" },
    { StringKey::ImageEditFillLabel,       "Fill" },
    { StringKey::ImageEditCopyBtn,         "Copy" },
    { StringKey::ImageEditPasteBtn,        "Paste" },
    { StringKey::ImageEditDocSection,      "Document" },

    // ── PDF page extraction ──────────────────────────────────────────────────
    { StringKey::CtxExtractPage,           "Extract page" },
    { StringKey::CtxExtractPages,          "Extract multiple pages…" },
    { StringKey::ExtractNameTitle,         "Name the new PDF" },
    { StringKey::ExtractNameLabel,         "File name" },
    { StringKey::ExtractCreateBtn,         "Extract" },
    { StringKey::ExtractDialogTitle,       "Extract pages" },
    { StringKey::ExtractGlobalTitle,       "Extract PDF pages from folder" },
    { StringKey::ExtractHintCtrl,          "Click to select and deselect pages. Hold Ctrl and hover a page to see a large preview." },
    { StringKey::ExtractSelectedCount,     "%1 pages selected" },
    { StringKey::ExtractNoPdfs,            "There are no PDF files in this folder." },
    { StringKey::FilterExtractBtn,         "Extract" },
    { StringKey::ExtractOkToast,           "PDF created: %1" },
    { StringKey::ExtractFailToast,         "Extraction failed." },
    { StringKey::ExtractProgressToast,     "Extracting page %1/%2" },
    { StringKey::ExtractPageShort,         "p. %1" },
    { StringKey::SettingsViewExtractStyle,     "PDF extraction: selection style" },
    { StringKey::SettingsViewExtractStyleHint, "How selected pages are highlighted in the extraction dialog." },
    { StringKey::ExtractStyleFrame,        "Frame" },
    { StringKey::ExtractStyleOverlay,      "Overlay" },
    { StringKey::SettingsPdfPageEditLabel,   "Add / remove pages" },
    { StringKey::SettingsPdfPageEditHint,    "In PDF edit mode, the “+” line beneath a page inserts a blank A4 page; right-clicking a page offers “Remove page”. Ctrl+Z undoes both." },
    { StringKey::PdfPageEditNonDestructive,  "Non-destructive (changes apply on export)" },
    { StringKey::PdfPageEditDestructiveMode, "Destructive (modify the original PDF immediately)" },
    { StringKey::PdfAddPageTip,              "Insert a blank A4 page here" },
    { StringKey::PdfRemovePage,              "Remove page" },
    { StringKey::SettingsGenShortcuts,       "Keyboard Shortcuts" },
    { StringKey::ShortcutCtxGallery,         "Gallery" },
    { StringKey::ShortcutCtxViewer,          "Media Viewer" },
    { StringKey::ShortcutCtxPdf,             "PDF Editor" },
    { StringKey::ShortcutCtxImage,           "Image Editor" },
    { StringKey::ShortcutCtxDocx,            "DOCX Editor" },
    { StringKey::ShortcutCtxText,            "Text Editor" },
    { StringKey::SettingsViewExtractLayout,     "Extraction dialog layout" },
    { StringKey::SettingsViewExtractLayoutHint, "Workbench: PDF list, page grid and a selection bar with a freely reorderable order. Compact: a plain single grid." },
    { StringKey::ExtractLayoutWorkbench,        "Workbench (default)" },
    { StringKey::ExtractLayoutCompact,          "Compact (minimal)" },
    { StringKey::ExtractWorkPdfs,               "PDFs" },
    { StringKey::ExtractWorkPages,              "Pages" },
    { StringKey::ExtractWorkOrder,              "Selection · order = output" },
    { StringKey::ExtractWorkHint,               "Click a page or drag it into the bar · drag inside the bar to reorder · drag out of the bar to remove" },
    { StringKey::ExtractWorkDropHint,           "Drag pages or whole PDFs here" },

};

// ─────────────────────────────────────────────────────────────────────────────
// Lookup
// ─────────────────────────────────────────────────────────────────────────────
QString Strings::get(StringKey key, Language lang) {
    const QMap<StringKey, QString>& map = (lang == Language::English) ? s_en : s_de;
    return map.value(key, QStringLiteral("?"));
}

QString Strings::get(StringKey key) {
    return get(key, AppSettings::instance().language());
}

// Name→Key→String: erlaubt reaktiven QML-Zugriff via App.uiText(App.language, "KeyName").
// Fallback (unbekannter Name) gibt den Namen zurück → Tippfehler sind sofort sichtbar.
QString Strings::byName(const QString& name, Language lang) {
    static const QMetaEnum me = QMetaEnum::fromType<StringKey>();
    bool ok = false;
    const int v = me.keyToValue(name.toUtf8().constData(), &ok);
    return ok ? get(static_cast<StringKey>(v), lang) : name;
}

QString Strings::get(StringKey key, const QString& arg1) {
    return get(key).arg(arg1);
}

#include "moc_Strings.cpp"
