#include "Strings.h"
#include <QMap>
#include <QMetaEnum>

// ─────────────────────────────────────────────────────────────────────────────
// German strings
// ─────────────────────────────────────────────────────────────────────────────
static const QMap<StringKey, QString> s_de = {
    { StringKey::MenuFile,              "&Datei" },
    { StringKey::MenuView,              "&Ansicht" },
    { StringKey::MenuSettings,          "&Einstellungen" },
    { StringKey::MenuOpenFolder,        "Ordner öffnen…" },
    { StringKey::MenuRefresh,           "Neu laden (R)" },
    { StringKey::MenuQuit,              "Beenden" },
    { StringKey::MenuToggleOptions,     "Optionen ein/aus (Alt+S)" },
    { StringKey::MenuSettingsItem,      "Einstellungen…" },
    { StringKey::MenuLanguage,          "Sprache" },
    { StringKey::MenuVideoPlayback,     "Video-Wiedergabe" },
    { StringKey::MenuVideoNative,       "Nativ" },
    { StringKey::MenuVideoExternal,     "Externer Player" },

    { StringKey::FilterAudio,           "Audio" },
    { StringKey::FilterMedia,           "Medien" },
    { StringKey::FilterDate,            "Datum" },
    { StringKey::FilterName,            "Name" },
    { StringKey::FilterTags,            "Tags" },
    { StringKey::FilterFileSize,        "Dateigröße" },
    { StringKey::FilterTagModeAnd,      "UND" },
    { StringKey::FilterTagModeOr,       "ODER" },
    { StringKey::FilterTagModeNur,      "NUR" },
    { StringKey::FilterTagModeInklusiv, "INKLUSIV" },


    { StringKey::SettingsTitle,         "Einstellungen" },
    { StringKey::SettingsTabGeneral,    "Allgemein" },
    { StringKey::SettingsTabDesign,     "Design" },
    { StringKey::SettingsLanguageLabel, "Sprache:" },
    { StringKey::SettingsOk,            "OK" },
    { StringKey::SettingsCancel,        "Abbrechen" },
    { StringKey::SettingsTagDelete,     "Tag löschen" },

    { StringKey::MetaTitle,         "Datum bearbeiten" },
    { StringKey::MetaReset,         "Zurücksetzen" },

    { StringKey::TagBarPlaceholder,     "Tag hinzufügen…" },
    { StringKey::TagBarDropdownHeader,  "Tag hinzufügen" },

    { StringKey::CatPanelAddCategory,   "Neue Kategorie" },
    { StringKey::CatPanelNewSubcategory,"Neue Unterkategorie" },
    { StringKey::CatPanelRename,        "Umbenennen" },
    { StringKey::CatPanelDelete,        "Kategorie löschen" },
    { StringKey::CatPanelSetColor,      "Einheitsfarbe setzen" },
    { StringKey::CatPanelNewTag,        "Neuer Tag" },


    { StringKey::FilterCatNewName,      "Neuer Name:" },
    { StringKey::FilterTagRenamePrompt, "Tag umbenennen" },

    { StringKey::SettingsTabCategories,  "Kategorien" },
    { StringKey::SettingsCatAdd,         "+ Kategorie" },
    { StringKey::SettingsCatNewLabel,    "Name:" },
    { StringKey::SettingsCatRenameTitle, "Kategorie umbenennen" },
    { StringKey::SettingsTagColorTitle,  "Tag-Farbe" },

    { StringKey::SettingsDesignBaseColors,      "Grundfarben" },
    { StringKey::SettingsDesignBgGradient,      "Hintergrund-Verlauf" },
    { StringKey::SettingsDesignAccent,          "Akzent" },
    { StringKey::SettingsDesignAccentSolid,     "Einfarbig" },
    { StringKey::SettingsDesignAccentGradient,  "Verlauf" },
    { StringKey::SettingsDesignTileTransparent, "Transparent" },
    { StringKey::SettingsDesignExportTitle,     "Theme exportieren" },
    { StringKey::SettingsDesignImportTitle,     "Theme importieren" },

    // Converter
    { StringKey::ConverterTagToSubcat,    "Tag → Unterkategorie" },
    { StringKey::ConverterSubcatToTag,    "Unterkategorie → Tag" },
    { StringKey::ConverterTagToCat,       "Tag → Kategorie" },
    { StringKey::ConverterCatToTag,       "Kategorie → Tag" },
    { StringKey::ConverterSubcatToCat,    "Unterkategorie → Kategorie" },
    { StringKey::ConverterCatToSubcat,    "Kategorie → Unterkategorie" },

    // Design – PDF viewer / sidebar / button colors

    // Uniform-color UI (replaces hardcoded German strings)

    // Hauptfenster-Leisten

    // Converter – lokalisierte Hinweistexte

    // PdfViewer – lokalisierte Texte

    // Saved Folders / Bookmarks
    { StringKey::MenuBookmarks,          "&Ordner" },
    { StringKey::MenuBookmarksEmpty,     "(keine gespeicherten Ordner)" },
    { StringKey::BookmarkAdd,            "Ordner hinzufügen" },
    { StringKey::BookmarkEdit,           "Bearbeiten" },
    { StringKey::BookmarkDelete,         "Löschen" },
    { StringKey::BookmarkPathLabel,      "Pfad:" },
    { StringKey::BookmarkBrowse,         "Durchsuchen…" },

    { StringKey::EditorAutoSave,         "Auto-Speichern aktivieren" },
    { StringKey::EditorSave,             "Speichern" },
    // ── Migration: vereinheitlichte UI-Strings ──
    { StringKey::SettingsGenFullscreenAnim,  "Vollbild-Animation" },
    { StringKey::SettingsGenAnimSlide,  "Verschieben (seitlich)" },
    { StringKey::SettingsGenAnimFade,  "Überblenden (weicher Zoom)" },
    { StringKey::SettingsGenAudioPlayer,  "Audio-Player" },
    { StringKey::SettingsGenAudioAccentTheme,  "Theme-Akzentfarbe" },
    { StringKey::SettingsGenAudioAccentApple,  "Apple-Blau" },
    { StringKey::SettingsGenRenderBackend,  "Render-Backend" },
    { StringKey::SettingsGenBackendLabel,  "Backend:" },
    { StringKey::SettingsGenBackendAuto,  "Auto" },
    { StringKey::SettingsGenBackendSoftware,  "Software (kein GPU)" },
    { StringKey::SettingsGenActiveBackend,  "Aktuell aktiv: %1  —  Änderungen werden beim nächsten Start wirksam." },
    { StringKey::SettingsGenSoftwareWarning,  "⚠  Software-Renderer aktiv. Möglicherweise wurde beim letzten Start ein inkompatibles Backend erkannt und automatisch zurückgesetzt." },
    { StringKey::SettingsGenVideoInternal,  "Intern (eingebauter Player)" },
    { StringKey::SettingsGenVideoExternal,  "Extern (System-Player)" },
    { StringKey::SettingsGenSaveClose,  "Speichern & Schließen" },
    { StringKey::SettingsViewTileSize,  "Kachelgröße" },
    { StringKey::SettingsViewWidth,  "Breite:" },
    { StringKey::SettingsViewHeight,  "Höhe:" },
    { StringKey::SettingsViewTileArrangement,  "Kachel-Anordnung" },
    { StringKey::SettingsViewAlignLeft,  "Linksbündig" },
    { StringKey::SettingsViewAlignCenter,  "Zentriert" },
    { StringKey::SettingsViewAlignRight,  "Rechtsbündig" },
    { StringKey::SettingsViewAlignManual,  "Manuell (freier Bereich)" },
    { StringKey::SettingsViewArrangementHint,  "Bestimmt, wie Kacheln innerhalb des sichtbaren Bereichs ausgerichtet werden." },
    { StringKey::SettingsViewZoomHint,  "<b>Zoom-Shortcuts:</b><br>Strg + Mausrad → Kachelgröße ändern<br>Strg + + / Strg + − → Kachelgröße stufenweise" },
    { StringKey::SettingsDesignProfileLabel,  "Design-Profil" },
    { StringKey::SettingsDesignCustomHint,  "Wähle das Profil „Custom“, um eigene Farben zu bearbeiten." },
    { StringKey::SettingsDesignTextPrimary,  "Text primär" },
    { StringKey::SettingsDesignTextMuted,  "Text gedämpft" },
    { StringKey::SettingsDesignFrame,  "Rahmen" },
    { StringKey::SettingsDesignBackground,  "Hintergrund" },
    { StringKey::SettingsDesignAccentType,  "Akzent-Typ" },
    { StringKey::SettingsDesignAccentColorLabel,  "Akzentfarbe" },
    { StringKey::SettingsDesignAccentGradEnd,  "Akzent Verlauf-Ende" },
    { StringKey::SettingsDesignGradStartLabel,  "Verlauf Start" },
    { StringKey::SettingsDesignGradEndLabel,  "Verlauf Ende" },
    { StringKey::SettingsDesignGradAngle,  "Verlauf-Winkel" },
    { StringKey::SettingsDesignAngleLabel,  "Winkel" },
    { StringKey::SettingsDesignGlow,  "Glow" },
    { StringKey::SettingsDesignGlowRadiusLabel,  "Glow-Radius" },
    { StringKey::SettingsDesignGlowIntensityLabel,  "Glow-Intensität" },
    { StringKey::SettingsDesignGlowHover,  "Glow beim Überfahren" },
    { StringKey::SettingsDesignCardTile,  "Karte / Kachel" },
    { StringKey::SettingsDesignTileBgLabel,  "Kachel-Hintergrund" },
    { StringKey::SettingsDesignTileColorLabel,  "Kachel-Farbe" },
    { StringKey::SettingsDesignTileGradEndLabel,  "Kachel Verlauf-Ende" },
    { StringKey::SettingsDesignGradInsteadSolid,  "Verlauf statt Einfarbig" },
    { StringKey::SettingsDesignTypeLabel,  "Typ" },
    { StringKey::SettingsDesignBars,  "Leisten" },
    { StringKey::SettingsDesignMenuBar,  "Menüleiste" },
    { StringKey::SettingsDesignToolbar,  "Werkzeugleiste" },
    { StringKey::SettingsDesignFilterBar,  "Filterleiste" },
    { StringKey::SettingsDesignStatusBar,  "Statusleiste" },
    { StringKey::SettingsDesignPdfViewer,  "PDF-Betrachter" },
    { StringKey::SettingsDesignSidebar,  "Seitenleiste" },
    { StringKey::SettingsDesignScrollbar,  "Scrollleiste" },
    { StringKey::SettingsDesignViewerBg,  "Betrachter-Hintergrund" },
    { StringKey::SettingsDesignThumbBg,  "Thumbnail-Hintergrund" },
    { StringKey::SettingsDesignThemeNameExport,  "Theme-Name & Export" },
    { StringKey::SettingsDesignExportBtn,  "Exportieren…" },
    { StringKey::SettingsDesignImportBtn,  "Importieren…" },
    { StringKey::SettingsDesignApplyBtn,  "Übernehmen" },
    { StringKey::SettingsDesignThemeFileFilter,  "Theme-Dateien (*.json)" },
    { StringKey::SettingsDesignAllFilesFilter,  "Alle Dateien (*)" },
    { StringKey::SettingsConvTagLabel,  "Tag:" },
    { StringKey::SettingsConvTargetCat,  "Ziel-Kategorie:" },
    { StringKey::SettingsConvSubcatLabel,  "Unterkategorie:" },
    { StringKey::SettingsConvCatLabel,  "Kategorie:" },
    { StringKey::SettingsConvModeLabel,  "Richtung:" },
    { StringKey::SettingsConvConvertBtn,  "Umwandeln" },
    { StringKey::SettingsConvTagToSubHint,  "Wandelt einen globalen Tag in eine Unterkategorie um. Der Tag wird danach aus der globalen Liste entfernt." },
    { StringKey::SettingsConvSubToTagHint,  "Wandelt eine Unterkategorie zurück in einen globalen Tag. Alle Dateien der Unterkategorie erhalten diesen Tag." },
    { StringKey::SettingsConvTagToCatHint,  "Wandelt einen globalen Tag in eine eigenständige Hauptkategorie um. Der Tag wird danach aus der globalen Liste entfernt." },
    { StringKey::SettingsConvCatToTagHint,  "Wandelt eine Hauptkategorie in einen globalen Tag um. Alle Dateien der Kategorie erhalten diesen Tag; enthaltene Unterkategorien werden mit entfernt." },
    { StringKey::SettingsConvSubToCatHint,  "Hebt eine Unterkategorie (samt Inhalt) auf die Hauptebene an — sie wird zur eigenständigen Kategorie." },
    { StringKey::SettingsConvCatToSubHint,  "Ordnet eine Hauptkategorie (samt Inhalt) einer anderen Kategorie unter. Das Ziel darf nicht innerhalb der verschobenen Kategorie liegen." },
    { StringKey::SettingsBookBtnAdd,  "+ Ordner hinzufügen" },
    { StringKey::SettingsBookHint,  "Schnellzugriff auf häufig genutzte Ordner." },
    { StringKey::SettingsBookEmpty,  "Noch keine Lesezeichen vorhanden." },
    { StringKey::SettingsBookAddTitle,  "Lesezeichen hinzufügen" },
    { StringKey::SettingsBookEditTitle,  "Lesezeichen bearbeiten" },
    { StringKey::SettingsBookDeleteTitle,  "Lesezeichen löschen" },
    { StringKey::SettingsBookDeleteConfirm,  "Dieses Lesezeichen wirklich entfernen?" },
    { StringKey::SettingsBookFolderPath,  "Ordnerpfad" },
    { StringKey::SettingsBookDisplayName,  "Anzeigename (optional)" },
    { StringKey::SettingsBookChooseFolder,  "Ordner wählen" },
    { StringKey::SettingsCatBtnNew,  "+ Neue Kategorie" },
    { StringKey::SettingsCatHintNew,  "Kategorien und Unterkategorien verwalten. Tags lassen sich Kategorien zuordnen." },
    { StringKey::SettingsCatEmptyNew,  "Noch keine Kategorien vorhanden." },
    { StringKey::SettingsCatColorLabel,  "Farbe:" },
    { StringKey::SettingsCatInheritSub,  "An Unterkategorien vererben" },
    { StringKey::SettingsCatDeleteConfirm,  "Kategorie „%1\" und alle Unterkategorien löschen?" },
    { StringKey::SettingsTagsBtnNew,  "+ Neuer Tag" },
    { StringKey::SettingsTagsHintNew,  "Tags umbenennen, einfärben oder löschen. Änderungen wirken global." },
    { StringKey::SettingsTagsEmpty,  "Noch keine Tags vorhanden." },
    { StringKey::SettingsTagsName,  "Tag-Name" },
    { StringKey::SettingsTagsDeleteConfirm,  "Tag „%1\" wirklich löschen? Er wird aus allen Dateien entfernt." },
    { StringKey::SettingsCatNodeAddSub,  "Unterkategorie…" },
    { StringKey::SettingsCatNodeRename,  "Umbenennen…" },
    { StringKey::SettingsCatNodeSetUniform,  "Einheitsfarbe setzen…" },
    { StringKey::SettingsCatNodeClearUniform,  "Einheitsfarbe entfernen" },
    { StringKey::SettingsCatNodeColorTitle,  "Kategorie-Farbe" },
    { StringKey::SettingsTabViewLayout,  "Ansicht / Layout" },
    { StringKey::SettingsTabEditorShort,  "Editor" },
    { StringKey::SettingsTabConverter,  "Converter" },
    { StringKey::SettingsTabBookmarks,  "Lesezeichen" },
    { StringKey::SettingsClose,  "Schließen" },
    { StringKey::SettingsEditorAutoSaveGroup,  "Automatisches Speichern" },
    { StringKey::SettingsEditorIntervalLabel,  "Intervall:" },
    { StringKey::ColorPickerTitle,  "Farbe wählen" },
    { StringKey::TileSizeHint,  "Ziehe den Eck-Griff der ersten Kachel, um die bevorzugte Kachelgröße einzustellen." },
    { StringKey::MenuTileSize,  "Kachelgröße…" },
    { StringKey::TagPanelEmpty,  "Noch keine Kategorien." },
    { StringKey::TagPanelDeleteTitle,  "Kategorie löschen?" },
    { StringKey::CatNodeRemoveFromCat,  "Aus Kategorie entfernen" },
    { StringKey::FilterNoTagsShort,  "Keine Tags vorhanden" },
    { StringKey::ViewerOpenedExternal,  "Im externen Player geöffnet." },
    { StringKey::ViewerNoRenderer,  "Kein Vorschau-Renderer für diesen Typ." },
    { StringKey::PdfPageIndicator,  "Seite %1 / %2" },
    { StringKey::PdfAudioPanelHeader,  "Audio · Seite %1" },
    { StringKey::PdfNoAudioOnPage,  "Keine Audios auf dieser Seite." },
    { StringKey::PdfAudioItemLabel,  "Audio %1" },

    // ── Batch 2 ──
    { StringKey::FilterModeAnyDesc,  "Mindestens einer der gewählten Tags" },
    { StringKey::FilterModeAllDesc,  "Alle gewählten Tags müssen vorhanden sein" },
    { StringKey::FilterModeExclusiveDesc,  "Ausschließlich die gewählten Tags" },
    { StringKey::FilterModeInclusiveDesc,  "Enthält die gewählten Tags (inklusiv)" },
    { StringKey::FilterSortLabel,  "Sortieren:" },
    { StringKey::FilterSortDesc,  "Absteigend" },
    { StringKey::FilterSortAsc,  "Aufsteigend" },
    { StringKey::FilterTagModeLabel,  "Tag-Filtermodus" },
    { StringKey::FilterActiveSuffix,  " aktiv" },
    { StringKey::FilterShowMediaTypes,  "Medientypen anzeigen" },
    { StringKey::FilterTagsToFilter,  "Tags zum Filtern" },
    { StringKey::ModeGroup,  "Gruppen-Modus" },
    { StringKey::ModeAddToTag,  "Add-to-Tag-Modus" },
    { StringKey::ViewerRandom,  "Zufällig" },
    { StringKey::GalleryNoMedia,  "Keine anzeigbaren Medien in diesem Ordner." },
    { StringKey::GalleryNoFolder,  "Kein Ordner geöffnet — Datei ▸ Ordner öffnen oder hierher ziehen." },
    { StringKey::DateYear,  "Jahr" },
    { StringKey::DateMonth,  "Monat" },
    { StringKey::DateDay,  "Tag" },
    { StringKey::DateHour,  "Stunde" },
    { StringKey::DateMinute,  "Minute" },
    { StringKey::PdfLoadError,  "PDF konnte nicht geladen werden." },
    { StringKey::PdfCollapsePreview,  "Seitenvorschau einklappen" },
    { StringKey::PdfExpandPreview,  "Seitenvorschau ausklappen" },
    { StringKey::PdfHideAudioBar,  "Audioleiste ausblenden" },
    { StringKey::PdfShowAudioBar,  "Audioleiste einblenden" },
    { StringKey::PdfFitPage,  "Ganze Seite" },
    { StringKey::PdfFitWidth,  "Breite" },
    { StringKey::PdfAudioActiveTitle,  "Audio %1 · S. %2" },
    { StringKey::ViewerShowPreview,  "Vorschau anzeigen" },
    { StringKey::ViewerShowSource,   "Quelltext anzeigen" },
    { StringKey::ViewerPreviewCrashed, "Vorschau abgestürzt — über den Button oben zur Quelltext-Ansicht wechseln oder die Datei neu öffnen." },
    { StringKey::FilterAddTagBtn,  "Hinzufügen" },
    { StringKey::FilterAddTagPlaceholder,  "Tag eingeben…" },
    { StringKey::CtxAddTag,  "Tag hinzufügen" },
    { StringKey::CtxAddCategory,  "Kategorie hinzufügen" },
    { StringKey::CtxNoCategories,  "Keine Kategorien vorhanden" },
    { StringKey::OverlayShowTags,  "Tags anzeigen" },
    { StringKey::OverlayShowCategories,  "Kategorien anzeigen" },
    { StringKey::OverlayNoValues,  "— keine —" },

    { StringKey::PanelSectionTags,     "Tags" },
    { StringKey::PanelAddTagTip,       "Neuen Tag erstellen" },
    { StringKey::PanelAddCategoryTip,  "Neue Kategorie erstellen" },
    { StringKey::PanelNoTags,          "Noch keine Tags." },
    { StringKey::FilterTagsCatsLabel,  "Tags & Kategorien" },
    { StringKey::FilterPanelHeader,    "Seitenpanel" },
    { StringKey::FilterTagPanelRow,    "Tag-Panel" },
    { StringKey::FilterCatPanelRow,    "Kategorie-Panel" },

};

// ─────────────────────────────────────────────────────────────────────────────
// English strings
// ─────────────────────────────────────────────────────────────────────────────
static const QMap<StringKey, QString> s_en = {
    { StringKey::MenuFile,              "&File" },
    { StringKey::MenuView,              "&View" },
    { StringKey::MenuSettings,          "&Settings" },
    { StringKey::MenuOpenFolder,        "Open Folder…" },
    { StringKey::MenuRefresh,           "Reload (R)" },
    { StringKey::MenuQuit,              "Quit" },
    { StringKey::MenuToggleOptions,     "Toggle Options (Alt+S)" },
    { StringKey::MenuSettingsItem,      "Settings…" },
    { StringKey::MenuLanguage,          "Language" },
    { StringKey::MenuVideoPlayback,     "Video Playback" },
    { StringKey::MenuVideoNative,       "Native" },
    { StringKey::MenuVideoExternal,     "External Player" },

    { StringKey::FilterAudio,           "Audio" },
    { StringKey::FilterMedia,           "Media" },
    { StringKey::FilterDate,            "Date" },
    { StringKey::FilterName,            "Name" },
    { StringKey::FilterTags,            "Tags" },
    { StringKey::FilterFileSize,        "File Size" },
    { StringKey::FilterTagModeAnd,      "AND" },
    { StringKey::FilterTagModeOr,       "OR" },
    { StringKey::FilterTagModeNur,      "ONLY" },
    { StringKey::FilterTagModeInklusiv, "INCLUSIVE" },


    { StringKey::SettingsTitle,         "Settings" },
    { StringKey::SettingsTabGeneral,    "General" },
    { StringKey::SettingsTabDesign,     "Design" },
    { StringKey::SettingsLanguageLabel, "Language:" },
    { StringKey::SettingsOk,            "OK" },
    { StringKey::SettingsCancel,        "Cancel" },
    { StringKey::SettingsTagDelete,     "Delete tag" },

    { StringKey::MetaTitle,         "Edit Date" },
    { StringKey::MetaReset,         "Reset" },

    { StringKey::TagBarPlaceholder,     "Add tag…" },
    { StringKey::TagBarDropdownHeader,  "Add tag" },

    { StringKey::CatPanelAddCategory,   "New Category" },
    { StringKey::CatPanelNewSubcategory,"New Subcategory" },
    { StringKey::CatPanelRename,        "Rename" },
    { StringKey::CatPanelDelete,        "Delete Category" },
    { StringKey::CatPanelSetColor,      "Set uniform color" },
    { StringKey::CatPanelNewTag,        "New tag" },


    { StringKey::FilterCatNewName,      "New name:" },
    { StringKey::FilterTagRenamePrompt, "Rename Tag" },

    { StringKey::SettingsTabCategories,  "Categories" },
    { StringKey::SettingsCatAdd,         "+ Category" },
    { StringKey::SettingsCatNewLabel,    "Name:" },
    { StringKey::SettingsCatRenameTitle, "Rename Category" },
    { StringKey::SettingsTagColorTitle,  "Tag Color" },

    { StringKey::SettingsDesignBaseColors,      "Base Colors" },
    { StringKey::SettingsDesignBgGradient,      "Background Gradient" },
    { StringKey::SettingsDesignAccent,          "Accent" },
    { StringKey::SettingsDesignAccentSolid,     "Solid" },
    { StringKey::SettingsDesignAccentGradient,  "Gradient" },
    { StringKey::SettingsDesignTileTransparent, "Transparent" },
    { StringKey::SettingsDesignExportTitle,     "Export Theme" },
    { StringKey::SettingsDesignImportTitle,     "Import Theme" },

    // Converter
    { StringKey::ConverterTagToSubcat,    "Tag → Subcategory" },
    { StringKey::ConverterSubcatToTag,    "Subcategory → Tag" },
    { StringKey::ConverterTagToCat,       "Tag → Category" },
    { StringKey::ConverterCatToTag,       "Category → Tag" },
    { StringKey::ConverterSubcatToCat,    "Subcategory → Category" },
    { StringKey::ConverterCatToSubcat,    "Category → Subcategory" },

    // Design – PDF viewer / sidebar / button colors

    // Uniform-color UI

    // Main-window chrome bars

    // Converter – localized hint texts

    // PdfViewer – localized texts

    // Saved Folders / Bookmarks
    { StringKey::MenuBookmarks,          "&Folders" },
    { StringKey::MenuBookmarksEmpty,     "(no saved folders)" },
    { StringKey::BookmarkAdd,            "Add Folder" },
    { StringKey::BookmarkEdit,           "Edit" },
    { StringKey::BookmarkDelete,         "Delete" },
    { StringKey::BookmarkPathLabel,      "Path:" },
    { StringKey::BookmarkBrowse,         "Browse…" },

    { StringKey::EditorAutoSave,         "Enable Auto-Save" },
    { StringKey::EditorSave,             "Save" },
    // ── Migration: vereinheitlichte UI-Strings ──
    { StringKey::SettingsGenFullscreenAnim,  "Fullscreen Animation" },
    { StringKey::SettingsGenAnimSlide,  "Slide (horizontal)" },
    { StringKey::SettingsGenAnimFade,  "Fade (soft zoom)" },
    { StringKey::SettingsGenAudioPlayer,  "Audio Player" },
    { StringKey::SettingsGenAudioAccentTheme,  "Theme accent color" },
    { StringKey::SettingsGenAudioAccentApple,  "Apple blue" },
    { StringKey::SettingsGenRenderBackend,  "Render Backend" },
    { StringKey::SettingsGenBackendLabel,  "Backend:" },
    { StringKey::SettingsGenBackendAuto,  "Auto" },
    { StringKey::SettingsGenBackendSoftware,  "Software (no GPU)" },
    { StringKey::SettingsGenActiveBackend,  "Currently active: %1  —  changes take effect on next start." },
    { StringKey::SettingsGenSoftwareWarning,  "⚠  Software renderer active. An incompatible backend may have been detected on the last start and reset automatically." },
    { StringKey::SettingsGenVideoInternal,  "Internal (built-in player)" },
    { StringKey::SettingsGenVideoExternal,  "External (system player)" },
    { StringKey::SettingsGenSaveClose,  "Save & Close" },
    { StringKey::SettingsViewTileSize,  "Tile Size" },
    { StringKey::SettingsViewWidth,  "Width:" },
    { StringKey::SettingsViewHeight,  "Height:" },
    { StringKey::SettingsViewTileArrangement,  "Tile Arrangement" },
    { StringKey::SettingsViewAlignLeft,  "Left-aligned" },
    { StringKey::SettingsViewAlignCenter,  "Centered" },
    { StringKey::SettingsViewAlignRight,  "Right-aligned" },
    { StringKey::SettingsViewAlignManual,  "Manual (free area)" },
    { StringKey::SettingsViewArrangementHint,  "Determines how tiles are aligned within the visible area." },
    { StringKey::SettingsViewZoomHint,  "<b>Zoom shortcuts:</b><br>Ctrl + mouse wheel → change tile size<br>Ctrl + + / Ctrl + − → tile size stepwise" },
    { StringKey::SettingsDesignProfileLabel,  "Design Profile" },
    { StringKey::SettingsDesignCustomHint,  "Select the \"Custom\" profile to edit your own colors." },
    { StringKey::SettingsDesignTextPrimary,  "Text primary" },
    { StringKey::SettingsDesignTextMuted,  "Text muted" },
    { StringKey::SettingsDesignFrame,  "Border" },
    { StringKey::SettingsDesignBackground,  "Background" },
    { StringKey::SettingsDesignAccentType,  "Accent type" },
    { StringKey::SettingsDesignAccentColorLabel,  "Accent color" },
    { StringKey::SettingsDesignAccentGradEnd,  "Accent gradient end" },
    { StringKey::SettingsDesignGradStartLabel,  "Gradient start" },
    { StringKey::SettingsDesignGradEndLabel,  "Gradient end" },
    { StringKey::SettingsDesignGradAngle,  "Gradient angle" },
    { StringKey::SettingsDesignAngleLabel,  "Angle" },
    { StringKey::SettingsDesignGlow,  "Glow" },
    { StringKey::SettingsDesignGlowRadiusLabel,  "Glow radius" },
    { StringKey::SettingsDesignGlowIntensityLabel,  "Glow intensity" },
    { StringKey::SettingsDesignGlowHover,  "Glow on hover" },
    { StringKey::SettingsDesignCardTile,  "Card / Tile" },
    { StringKey::SettingsDesignTileBgLabel,  "Tile background" },
    { StringKey::SettingsDesignTileColorLabel,  "Tile color" },
    { StringKey::SettingsDesignTileGradEndLabel,  "Tile gradient end" },
    { StringKey::SettingsDesignGradInsteadSolid,  "Gradient instead of solid" },
    { StringKey::SettingsDesignTypeLabel,  "Type" },
    { StringKey::SettingsDesignBars,  "Bars" },
    { StringKey::SettingsDesignMenuBar,  "Menu bar" },
    { StringKey::SettingsDesignToolbar,  "Toolbar" },
    { StringKey::SettingsDesignFilterBar,  "Filter bar" },
    { StringKey::SettingsDesignStatusBar,  "Status bar" },
    { StringKey::SettingsDesignPdfViewer,  "PDF Viewer" },
    { StringKey::SettingsDesignSidebar,  "Sidebar" },
    { StringKey::SettingsDesignScrollbar,  "Scrollbar" },
    { StringKey::SettingsDesignViewerBg,  "Viewer background" },
    { StringKey::SettingsDesignThumbBg,  "Thumbnail background" },
    { StringKey::SettingsDesignThemeNameExport,  "Theme name & export" },
    { StringKey::SettingsDesignExportBtn,  "Export…" },
    { StringKey::SettingsDesignImportBtn,  "Import…" },
    { StringKey::SettingsDesignApplyBtn,  "Apply" },
    { StringKey::SettingsDesignThemeFileFilter,  "Theme files (*.json)" },
    { StringKey::SettingsDesignAllFilesFilter,  "All files (*)" },
    { StringKey::SettingsConvTagLabel,  "Tag:" },
    { StringKey::SettingsConvTargetCat,  "Target category:" },
    { StringKey::SettingsConvSubcatLabel,  "Subcategory:" },
    { StringKey::SettingsConvCatLabel,  "Category:" },
    { StringKey::SettingsConvModeLabel,  "Direction:" },
    { StringKey::SettingsConvConvertBtn,  "Convert" },
    { StringKey::SettingsConvTagToSubHint,  "Converts a global tag into a subcategory. The tag is then removed from the global list." },
    { StringKey::SettingsConvSubToTagHint,  "Converts a subcategory back into a global tag. All files of the subcategory receive this tag." },
    { StringKey::SettingsConvTagToCatHint,  "Converts a global tag into a standalone top-level category. The tag is then removed from the global list." },
    { StringKey::SettingsConvCatToTagHint,  "Converts a top-level category into a global tag. All files of the category receive this tag; contained subcategories are removed as well." },
    { StringKey::SettingsConvSubToCatHint,  "Promotes a subcategory (including its contents) to the top level — it becomes a standalone category." },
    { StringKey::SettingsConvCatToSubHint,  "Places a top-level category (including its contents) under another category. The target must not lie inside the moved category." },
    { StringKey::SettingsBookBtnAdd,  "+ Add Folder" },
    { StringKey::SettingsBookHint,  "Quick access to frequently used folders." },
    { StringKey::SettingsBookEmpty,  "No saved folders yet." },
    { StringKey::SettingsBookAddTitle,  "Add Saved Folder" },
    { StringKey::SettingsBookEditTitle,  "Edit Saved Folder" },
    { StringKey::SettingsBookDeleteTitle,  "Delete Saved Folder" },
    { StringKey::SettingsBookDeleteConfirm,  "Really remove this saved folder?" },
    { StringKey::SettingsBookFolderPath,  "Folder path" },
    { StringKey::SettingsBookDisplayName,  "Display name (optional)" },
    { StringKey::SettingsBookChooseFolder,  "Choose Folder" },
    { StringKey::SettingsCatBtnNew,  "+ New Category" },
    { StringKey::SettingsCatHintNew,  "Manage categories and subcategories. Tags can be assigned to categories." },
    { StringKey::SettingsCatEmptyNew,  "No categories yet." },
    { StringKey::SettingsCatColorLabel,  "Color:" },
    { StringKey::SettingsCatInheritSub,  "Inherit to subcategories" },
    { StringKey::SettingsCatDeleteConfirm,  "Delete category \"%1\" and all subcategories?" },
    { StringKey::SettingsTagsBtnNew,  "+ New Tag" },
    { StringKey::SettingsTagsHintNew,  "Rename, recolor or delete tags. Changes apply globally." },
    { StringKey::SettingsTagsEmpty,  "No tags yet." },
    { StringKey::SettingsTagsName,  "Tag name" },
    { StringKey::SettingsTagsDeleteConfirm,  "Really delete tag \"%1\"? It will be removed from all files." },
    { StringKey::SettingsCatNodeAddSub,  "Subcategory…" },
    { StringKey::SettingsCatNodeRename,  "Rename…" },
    { StringKey::SettingsCatNodeSetUniform,  "Set uniform color…" },
    { StringKey::SettingsCatNodeClearUniform,  "Remove uniform color" },
    { StringKey::SettingsCatNodeColorTitle,  "Category Color" },
    { StringKey::SettingsTabViewLayout,  "View / Layout" },
    { StringKey::SettingsTabEditorShort,  "Editor" },
    { StringKey::SettingsTabConverter,  "Converter" },
    { StringKey::SettingsTabBookmarks,  "Saved Folders" },
    { StringKey::SettingsClose,  "Close" },
    { StringKey::SettingsEditorAutoSaveGroup,  "Automatic Saving" },
    { StringKey::SettingsEditorIntervalLabel,  "Interval:" },
    { StringKey::ColorPickerTitle,  "Choose Color" },
    { StringKey::TileSizeHint,  "Drag the corner handle of the first tile to set the preferred tile size." },
    { StringKey::MenuTileSize,  "Tile Size…" },
    { StringKey::TagPanelEmpty,  "No categories yet." },
    { StringKey::TagPanelDeleteTitle,  "Delete category?" },
    { StringKey::CatNodeRemoveFromCat,  "Remove from category" },
    { StringKey::FilterNoTagsShort,  "No tags available" },
    { StringKey::ViewerOpenedExternal,  "Opened in external player." },
    { StringKey::ViewerNoRenderer,  "No preview renderer for this type." },
    { StringKey::PdfPageIndicator,  "Page %1 / %2" },
    { StringKey::PdfAudioPanelHeader,  "Audio · Page %1" },
    { StringKey::PdfNoAudioOnPage,  "No audio on this page." },
    { StringKey::PdfAudioItemLabel,  "Audio %1" },

    // ── Batch 2 ──
    { StringKey::FilterModeAnyDesc,  "At least one of the selected tags" },
    { StringKey::FilterModeAllDesc,  "All selected tags must be present" },
    { StringKey::FilterModeExclusiveDesc,  "Exclusively the selected tags" },
    { StringKey::FilterModeInclusiveDesc,  "Contains the selected tags (inclusive)" },
    { StringKey::FilterSortLabel,  "Sort:" },
    { StringKey::FilterSortDesc,  "Descending" },
    { StringKey::FilterSortAsc,  "Ascending" },
    { StringKey::FilterTagModeLabel,  "Tag filter mode" },
    { StringKey::FilterActiveSuffix,  " active" },
    { StringKey::FilterShowMediaTypes,  "Show media types" },
    { StringKey::FilterTagsToFilter,  "Tags to filter" },
    { StringKey::ModeGroup,  "Group mode" },
    { StringKey::ModeAddToTag,  "Add-to-tag mode" },
    { StringKey::ViewerRandom,  "Random" },
    { StringKey::GalleryNoMedia,  "No displayable media in this folder." },
    { StringKey::GalleryNoFolder,  "No folder open — File ▸ Open folder or drag here." },
    { StringKey::DateYear,  "Year" },
    { StringKey::DateMonth,  "Month" },
    { StringKey::DateDay,  "Day" },
    { StringKey::DateHour,  "Hour" },
    { StringKey::DateMinute,  "Minute" },
    { StringKey::PdfLoadError,  "PDF could not be loaded." },
    { StringKey::PdfCollapsePreview,  "Collapse page preview" },
    { StringKey::PdfExpandPreview,  "Expand page preview" },
    { StringKey::PdfHideAudioBar,  "Hide audio bar" },
    { StringKey::PdfShowAudioBar,  "Show audio bar" },
    { StringKey::PdfFitPage,  "Whole page" },
    { StringKey::PdfFitWidth,  "Width" },
    { StringKey::PdfAudioActiveTitle,  "Audio %1 · p. %2" },
    { StringKey::ViewerShowPreview,  "Show preview" },
    { StringKey::ViewerShowSource,   "Show source" },
    { StringKey::ViewerPreviewCrashed, "Preview crashed — switch to source with the button above, or reopen the file." },
    { StringKey::FilterAddTagBtn,  "Add" },
    { StringKey::FilterAddTagPlaceholder,  "Enter tag…" },
    { StringKey::CtxAddTag,  "Add tag" },
    { StringKey::CtxAddCategory,  "Add category" },
    { StringKey::CtxNoCategories,  "No categories available" },
    { StringKey::OverlayShowTags,  "Show tags" },
    { StringKey::OverlayShowCategories,  "Show categories" },
    { StringKey::OverlayNoValues,  "— none —" },

    { StringKey::PanelSectionTags,     "Tags" },
    { StringKey::PanelAddTagTip,       "Create new tag" },
    { StringKey::PanelAddCategoryTip,  "Create new category" },
    { StringKey::PanelNoTags,          "No tags yet." },
    { StringKey::FilterTagsCatsLabel,  "Tags & Categories" },
    { StringKey::FilterPanelHeader,    "Side panel" },
    { StringKey::FilterTagPanelRow,    "Tag panel" },
    { StringKey::FilterCatPanelRow,    "Category panel" },

};

// ─────────────────────────────────────────────────────────────────────────────
// Lookup
// ─────────────────────────────────────────────────────────────────────────────
QString Strings::get(StringKey key, Language lang) {
    const QMap<StringKey, QString>& map = (lang == Language::English) ? s_en : s_de;
    return map.value(key, QStringLiteral("?"));
}

QString Strings::get(StringKey key) {
    return get(key, AppSettings::instance().language());
}

// Name→Key→String: erlaubt reaktiven QML-Zugriff via App.uiText(App.language, "KeyName").
// Fallback (unbekannter Name) gibt den Namen zurück → Tippfehler sind sofort sichtbar.
QString Strings::byName(const QString& name, Language lang) {
    static const QMetaEnum me = QMetaEnum::fromType<StringKey>();
    bool ok = false;
    const int v = me.keyToValue(name.toUtf8().constData(), &ok);
    return ok ? get(static_cast<StringKey>(v), lang) : name;
}

QString Strings::get(StringKey key, const QString& arg1) {
    return get(key).arg(arg1);
}

#include "moc_Strings.cpp"
