#pragma once
#include <QString>
#include <QObject>
#include "AppSettings.h"

/**
 * Central translation system.
 * All UI strings are looked up here via Language enum.
 * Add new keys to the StringKey enum, then add translations in Strings.cpp.
 */
namespace SK { Q_NAMESPACE
enum class StringKey {
    // MainWindow / Menus
    MenuFile,
    MenuView,
    MenuSettings,
    MenuOpenFolder,
    MenuRefresh,
    MenuQuit,
    MenuToggleOptions,
    MenuSettingsItem,
    MenuLanguage,
    MenuVideoPlayback,
    MenuVideoNative,
    MenuVideoExternal,
    StatusFolderLoaded,
    StatusRenamed,

    // FilterBar
    FilterImages,
    FilterVideos,
    FilterAudio,
    FilterPdf,
    FilterMedia,
    FilterSortBy,
    FilterDate,
    FilterName,
    FilterTags,
    FilterFileSize,
    FilterReverseOrder,
    FilterTagModeTooltip,
    FilterTagModeAnd,
    FilterTagModeOr,
    FilterTagModeNur,
    FilterTagModeInklusiv,

    // FullscreenView
    FullscreenBack,
    FullscreenFilenamePlaceholder,
    FullscreenEditDate,
    FullscreenDeleteFile,
    FullscreenPrev,
    FullscreenNext,
    FullscreenRandom,
    FullscreenImageLoadError,

    // SettingsDialog
    SettingsTitle,
    SettingsTabGeneral,
    SettingsTabTags,
    SettingsTabDesign,
    SettingsLanguageGroup,
    SettingsLanguageLabel,
    SettingsVideoGroup,
    SettingsVideoNative,
    SettingsVideoExternal,
    SettingsColorsGroup,
    SettingsColorBg,
    SettingsColorAccent,
    SettingsColorAndOr,
    SettingsColorReset,
    SettingsOk,
    SettingsCancel,
    SettingsTagsHint,
    SettingsTagChangeColor,
    SettingsTagDelete,
    SettingsTagDeleteTitle,
    SettingsTagDeleteMsg,
    SettingsTagEmpty,

    // MetadataEditor
    MetaTitle,
    MetaFile,
    MetaDate,
    MetaUseCustomDate,
    MetaReset,
    MetaOk,
    MetaCancel,

    // TagBar / TagWidget
    TagBarPlaceholder,
    TagBarDropdownTooltip,
    TagBarDropdownHeader,
    TagBarNoTags,
    TagBarCompactTooltip,

    // Category panel / context menus
    CatPanelAddCategory,
    CatPanelNewSubcategory,
    CatPanelRename,
    CatPanelDelete,
    CatPanelDeleteMsg,
    CatPanelSetColor,
    CatPanelAddTag,
    CatPanelNewTag,
    CatPanelAddToTagMode,
    CatPanelGroupMode,

    // GalleryView banners
    BannerGroupMode,
    BannerGroupModeCancel,
    BannerAddToTagMode,
    BannerAddToTagModeCancel,

    // FilterBar / HoverDropdown
    FilterAddCategory,
    FilterNewCategory,
    FilterCategoryColor,
    FilterNoCategories,
    FilterNoTags,
    FilterModePanelHeader,
    FilterModeOrTip,
    FilterModeAndTip,
    FilterModeNurTip,
    FilterModeInklusivTip,
    FilterCatRename,
    FilterCatRenamePrompt,
    FilterCatNewName,
    FilterCatChangeColor,
    FilterNewTag,
    FilterNewTagLabel,
    FilterCatAddSub,
    FilterCatNewSubPrompt,
    FilterCatDelete,
    FilterTagRename,
    FilterTagRenamePrompt,
    FilterTagNewName,
    FilterTagAlreadyIn,
    FilterTagAddTo,

    // SettingsDialog – Categories tab
    SettingsTabCategories,
    SettingsCatHint,
    SettingsCatAdd,
    SettingsCatEmpty,
    SettingsCatNewTitle,
    SettingsCatNewLabel,
    SettingsCatColorTitle,
    SettingsCatRenameTitle,
    SettingsCatRenameLabel,
    SettingsCatDeleteTitle,
    SettingsCatDeleteMsg,
    SettingsSubNewTitle,
    SettingsSubNewLabel,
    SettingsSubColorTitle,
    SettingsTagRenameTitle,
    SettingsTagRenameLabel,
    SettingsTagAdd,
    SettingsTagNewTitle,
    SettingsTagNewLabel,
    SettingsTagColorTitle,

    // SettingsDialog – Design tab
    SettingsDesignProfileGroup,
    SettingsCustomThemeEditor,
    SettingsDesignBaseColors,
    SettingsDesignColorBg2,
    SettingsDesignColorCard,
    SettingsDesignColorText,
    SettingsDesignColorMuted,
    SettingsDesignColorBorder,
    SettingsDesignBgGradient,
    SettingsDesignBgGradientEnable,
    SettingsDesignGradStart,
    SettingsDesignGradEnd,
    SettingsDesignAngle,
    SettingsDesignAccent,
    SettingsDesignType,
    SettingsDesignAccentSolid,
    SettingsDesignAccentGradient,
    SettingsDesignAccentGlow,
    SettingsDesignAccentColor,
    SettingsDesignGlowRadius,
    SettingsDesignGlowIntensity,
    SettingsDesignTileGroup,
    SettingsDesignTileBgType,
    SettingsDesignTileSolid,
    SettingsDesignTileGradient,
    SettingsDesignTileTransparent,
    SettingsDesignTileBg,
    SettingsDesignTileGradEnd,
    SettingsDesignTileAngle,
    SettingsDesignTileGlow,
    SettingsDesignTileGlowRadius,
    SettingsDesignThemeName,
    SettingsDesignApply,
    SettingsDesignExport,
    SettingsDesignImport,
    SettingsDesignExportTitle,
    SettingsDesignImportTitle,
    SettingsDesignExportOk,
    SettingsDesignExportErr,
    SettingsDesignImportOk,
    SettingsDesignImportErr,
    SettingsDesignProfileDark,
    SettingsDesignProfileDarkDesc,
    SettingsDesignProfileOLED,
    SettingsDesignProfileOLEDDesc,
    SettingsDesignProfileOcean,
    SettingsDesignProfileOceanDesc,
    SettingsDesignProfileInferno,
    SettingsDesignProfileInfernoDesc,
    SettingsDesignProfileNeon,
    SettingsDesignProfileNeonDesc,
    SettingsDesignProfileRose,
    SettingsDesignProfileRoseDesc,
    SettingsDesignProfileElegant,
    SettingsDesignProfileElegantDesc,
    SettingsDesignProfileSimple,
    SettingsDesignProfileSimpleDesc,
    SettingsDesignProfileCustom,
    SettingsDesignProfileCustomDesc,

    // Converter (Tag <-> Unterkategorie)
    ConverterTabTitle,
    ConverterTagToSubcat,
    ConverterSubcatToTag,
    ConverterSelectTag,
    ConverterSelectParentCat,
    ConverterSelectSubcat,
    ConverterNewSubcatName,
    ConverterConvert,
    ConverterSuccess,
    ConverterErrorNoTag,
    ConverterErrorNoCat,
    ConverterErrorNoSubcat,
    ConverterErrorNoName,
    ConverterMigrateJson,
    ConverterMigrateSuccess,
    ConverterMigrateError,
    ConverterMigrateConfirm,

    // Design – extra color rows (PDF viewer, sidebar, buttons)
    SettingsDesignPdfGroup,
    SettingsDesignPdfSidebarBg,
    SettingsDesignPdfToolbarBg,
    SettingsDesignPdfScrollbarBg,
    SettingsDesignPdfViewerBg,
    SettingsDesignPdfThumbBg,
    SettingsDesignButtonBg,
    SettingsDesignSidebarBg,

    // Uniform-color toggle tooltips (replaces hardcoded German)
    DesignUniformColorActive,
    DesignUniformColorInactive,
    DesignPickUniformColor,
    DesignInheritTitle,
    DesignInheritMsg,
    DesignInheritYes,
    DesignInheritNo,
    SettingsTagDuplicate,

    // Hauptfenster-Leisten Farben (menubar, toolbar, filterbar, statusbar)
    SettingsDesignChromeGroup,
    SettingsDesignMenuBarBg,
    SettingsDesignToolbarBg,
    SettingsDesignFilterBarBg,
    SettingsDesignStatusBarBg,

    // Converter – Texte die bisher nur mit tr() auf Englisch waren
    ConverterTagToSubcatHint,
    ConverterSubcatToTagHint,
    ConverterMigrateHint,
    ConverterPlaceholderEmptyName,

    // PDF viewer
    PdfPrevPageTooltip,
    PdfNextPageTooltip,
    PdfZoomOutTooltip,
    PdfZoomInTooltip,
    PdfScrollModeMulti,
    PdfScrollModeSingle,
    PdfScrollModeTooltip,
    PdfSidebarTooltip,
    PdfAudioLabel,
    PdfVideoTitle,
    PdfAudioCount,
    PdfVideoCount,
    PdfMediaClickHint,
    PdfAudioNotFound,
    PdfVideoNotFound,

    // Saved Folders / Bookmarks
    MenuBookmarks,
    MenuBookmarksEmpty,
    BookmarkSettingsTitle,
    BookmarkAdd,
    BookmarkEdit,
    BookmarkDelete,
    BookmarkDeleteConfirm,
    BookmarkPathLabel,
    BookmarkNameLabel,
    BookmarkNamePlaceholder,
    BookmarkPathPlaceholder,
    BookmarkBrowse,
    BookmarkNoName,
    BookmarkTabTitle,

    // Text editor / filter
    FilterText,
    SettingsTabEditor,
    EditorAutoSave,
    EditorAutoSaveInterval,
    EditorSave,
    EditorUnsavedTitle,
    EditorUnsavedMsg,
    EditorLoadError,
    EditorAutoSaveGroup,
    // ── Migration: vereinheitlichte UI-Strings (vormals qsTr/hartcodiert) ──
    SettingsGenFullscreenAnim,
    SettingsGenAnimSlide,
    SettingsGenAnimFade,
    SettingsGenAudioPlayer,
    SettingsGenAudioAccentTheme,
    SettingsGenAudioAccentApple,
    SettingsGenRenderBackend,
    SettingsGenBackendLabel,
    SettingsGenBackendAuto,
    SettingsGenBackendSoftware,
    SettingsGenActiveBackend,
    SettingsGenSoftwareWarning,
    SettingsGenVideoInternal,
    SettingsGenVideoExternal,
    SettingsGenSaveClose,
    SettingsViewTileSize,
    SettingsViewWidth,
    SettingsViewHeight,
    SettingsViewTileArrangement,
    SettingsViewAlignLeft,
    SettingsViewAlignCenter,
    SettingsViewAlignRight,
    SettingsViewAlignManual,
    SettingsViewArrangementHint,
    SettingsViewZoomHint,
    SettingsDesignProfileLabel,
    SettingsDesignCustomHint,
    SettingsDesignTextPrimary,
    SettingsDesignTextMuted,
    SettingsDesignFrame,
    SettingsDesignBackground,
    SettingsDesignAccentType,
    SettingsDesignAccentColorLabel,
    SettingsDesignAccentGradEnd,
    SettingsDesignGradStartLabel,
    SettingsDesignGradEndLabel,
    SettingsDesignGradAngle,
    SettingsDesignAngleLabel,
    SettingsDesignGlow,
    SettingsDesignGlowRadiusLabel,
    SettingsDesignGlowIntensityLabel,
    SettingsDesignGlowHover,
    SettingsDesignCardTile,
    SettingsDesignTileBgLabel,
    SettingsDesignTileColorLabel,
    SettingsDesignTileGradEndLabel,
    SettingsDesignGradInsteadSolid,
    SettingsDesignTypeLabel,
    SettingsDesignBars,
    SettingsDesignMenuBar,
    SettingsDesignToolbar,
    SettingsDesignFilterBar,
    SettingsDesignStatusBar,
    SettingsDesignPdfViewer,
    SettingsDesignSidebar,
    SettingsDesignScrollbar,
    SettingsDesignViewerBg,
    SettingsDesignThumbBg,
    SettingsDesignThemeNameExport,
    SettingsDesignExportBtn,
    SettingsDesignImportBtn,
    SettingsDesignApplyBtn,
    SettingsDesignThemeFileFilter,
    SettingsDesignAllFilesFilter,
    SettingsConvTagLabel,
    SettingsConvTargetCat,
    SettingsConvSubcatLabel,
    SettingsConvConvertBtn,
    SettingsConvTagToSubHint,
    SettingsConvSubToTagHint,
    SettingsConvJsonMigration,
    SettingsConvMigrateNow,
    SettingsConvMigrateHint,
    SettingsConvSaveV2Confirm,
    SettingsBookBtnAdd,
    SettingsBookHint,
    SettingsBookEmpty,
    SettingsBookAddTitle,
    SettingsBookEditTitle,
    SettingsBookDeleteTitle,
    SettingsBookDeleteConfirm,
    SettingsBookFolderPath,
    SettingsBookDisplayName,
    SettingsBookChooseFolder,
    SettingsCatBtnNew,
    SettingsCatHintNew,
    SettingsCatEmptyNew,
    SettingsCatColorLabel,
    SettingsCatInheritSub,
    SettingsCatDeleteConfirm,
    SettingsTagsBtnNew,
    SettingsTagsHintNew,
    SettingsTagsEmpty,
    SettingsTagsName,
    SettingsTagsDeleteConfirm,
    SettingsCatNodeAddSub,
    SettingsCatNodeRename,
    SettingsCatNodeSetUniform,
    SettingsCatNodeClearUniform,
    SettingsCatNodeColorTitle,
    SettingsTabViewLayout,
    SettingsTabEditorShort,
    SettingsTabConverter,
    SettingsTabBookmarks,
    SettingsClose,
    SettingsEditorAutoSaveGroup,
    SettingsEditorIntervalLabel,
    ColorPickerTitle,
    TileSizeHint,
    MenuTileSize,
    TagPanelEmpty,
    TagPanelDeleteTitle,
    CatNodeRemoveFromCat,
    FilterCatPanelHint,
    FilterNoTagsShort,
    FilterCatPanelTooltip,
    FilterCatPanelToggle,
    ViewerOpenedExternal,
    ViewerNoRenderer,
    PdfPageIndicator,
    PdfAudioPanelHeader,
    PdfNoAudioOnPage,
    PdfAudioItemLabel,

    // ── Batch 2: weitere vereinheitlichte UI-Strings ──
    FilterModeAnyDesc,
    FilterModeAllDesc,
    FilterModeExclusiveDesc,
    FilterModeInclusiveDesc,
    FilterSortLabel,
    FilterSortDesc,
    FilterSortAsc,
    FilterTagModeLabel,
    FilterActiveSuffix,
    FilterShowMediaTypes,
    FilterTagsToFilter,
    ModeGroup,
    ModeAddToTag,
    ViewerRandom,
    GalleryNoMedia,
    GalleryNoFolder,
    DateYear,
    DateMonth,
    DateDay,
    DateHour,
    DateMinute,
    PdfLoadError,
    PdfCollapsePreview,
    PdfExpandPreview,
    PdfHideAudioBar,
    PdfShowAudioBar,
    PdfFitPage,
    PdfFitWidth,
    PdfAudioActiveTitle,
};
Q_ENUM_NS(StringKey)
}  // namespace SK
using StringKey = SK::StringKey;

class Strings {
public:
    static QString get(StringKey key);
    static QString get(StringKey key, const QString& arg1);
    static QString get(StringKey key, Language lang);          // explizite Sprache
    static QString byName(const QString& name, Language lang); // Name→Key→String (für QML uiText)

private:
    static const QString& de(StringKey key);
    static const QString& en(StringKey key);
};
