#pragma once
#include <QString>
#include "AppSettings.h"

/**
 * Central translation system.
 * All UI strings are looked up here via Language enum.
 * Add new keys to the StringKey enum, then add translations in Strings.cpp.
 */
enum class StringKey {
    // MainWindow / Menus
    MenuFile,
    MenuView,
    MenuSettings,
    MenuOpenFolder,
    MenuRefresh,
    MenuQuit,
    MenuToggleOptions,
    MenuSettingsItem,
    MenuLanguage,
    MenuVideoPlayback,
    MenuVideoNative,
    MenuVideoExternal,
    StatusFolderLoaded,
    StatusRenamed,

    // FilterBar
    FilterImages,
    FilterVideos,
    FilterAudio,
    FilterMedia,
    FilterSortBy,
    FilterDate,
    FilterName,
    FilterTags,
    FilterFileSize,
    FilterReverseOrder,
    FilterTagModeTooltip,
    FilterTagModeAnd,
    FilterTagModeOr,
    FilterTagModeNur,
    FilterTagModeInklusiv,

    // FullscreenView
    FullscreenBack,
    FullscreenFilenamePlaceholder,
    FullscreenEditDate,
    FullscreenPrev,
    FullscreenNext,
    FullscreenRandom,
    FullscreenImageLoadError,

    // SettingsDialog
    SettingsTitle,
    SettingsTabGeneral,
    SettingsTabTags,
    SettingsTabDesign,
    SettingsLanguageGroup,
    SettingsLanguageLabel,
    SettingsVideoGroup,
    SettingsVideoNative,
    SettingsVideoExternal,
    SettingsColorsGroup,
    SettingsColorBg,
    SettingsColorAccent,
    SettingsColorAndOr,
    SettingsColorReset,
    SettingsOk,
    SettingsCancel,
    SettingsTagsHint,
    SettingsTagChangeColor,
    SettingsTagDelete,
    SettingsTagDeleteTitle,
    SettingsTagDeleteMsg,
    SettingsTagEmpty,

    // MetadataEditor
    MetaTitle,
    MetaFile,
    MetaDate,
    MetaUseCustomDate,
    MetaReset,
    MetaOk,
    MetaCancel,

    // TagBar / TagWidget
    TagBarPlaceholder,
    TagBarDropdownTooltip,
    TagBarDropdownHeader,
    TagBarNoTags,
    TagBarCompactTooltip,

    // Category panel / context menus
    CatPanelAddCategory,
    CatPanelNewSubcategory,
    CatPanelRename,
    CatPanelDelete,
    CatPanelDeleteMsg,
    CatPanelSetColor,
    CatPanelAddTag,
    CatPanelNewTag,
    CatPanelAddToTagMode,
    CatPanelGroupMode,

    // GalleryView banners
    BannerGroupMode,
    BannerGroupModeCancel,
    BannerAddToTagMode,
    BannerAddToTagModeCancel,

    // FilterBar / HoverDropdown
    FilterAddCategory,
    FilterNewCategory,
    FilterCategoryColor,
    FilterNoCategories,
    FilterNoTags,
    FilterModePanelHeader,
    FilterModeOrTip,
    FilterModeAndTip,
    FilterModeNurTip,
    FilterModeInklusivTip,
    FilterCatRename,
    FilterCatRenamePrompt,
    FilterCatNewName,
    FilterCatChangeColor,
    FilterNewTag,
    FilterNewTagLabel,
    FilterCatAddSub,
    FilterCatNewSubPrompt,
    FilterCatDelete,
    FilterTagRename,
    FilterTagRenamePrompt,
    FilterTagNewName,
    FilterTagAlreadyIn,
    FilterTagAddTo,

    // SettingsDialog – Categories tab
    SettingsTabCategories,
    SettingsCatHint,
    SettingsCatAdd,
    SettingsCatEmpty,
    SettingsCatNewTitle,
    SettingsCatNewLabel,
    SettingsCatColorTitle,
    SettingsCatRenameTitle,
    SettingsCatRenameLabel,
    SettingsCatDeleteTitle,
    SettingsCatDeleteMsg,
    SettingsSubNewTitle,
    SettingsSubNewLabel,
    SettingsSubColorTitle,
    SettingsTagRenameTitle,
    SettingsTagRenameLabel,
    SettingsTagAdd,
    SettingsTagNewTitle,
    SettingsTagNewLabel,
    SettingsTagColorTitle,

    // SettingsDialog – Design tab
    SettingsDesignProfileGroup,
    SettingsCustomThemeEditor,
    SettingsDesignBaseColors,
    SettingsDesignColorBg2,
    SettingsDesignColorCard,
    SettingsDesignColorText,
    SettingsDesignColorMuted,
    SettingsDesignColorBorder,
    SettingsDesignBgGradient,
    SettingsDesignBgGradientEnable,
    SettingsDesignGradStart,
    SettingsDesignGradEnd,
    SettingsDesignAngle,
    SettingsDesignAccent,
    SettingsDesignType,
    SettingsDesignAccentSolid,
    SettingsDesignAccentGradient,
    SettingsDesignAccentGlow,
    SettingsDesignAccentColor,
    SettingsDesignGlowRadius,
    SettingsDesignGlowIntensity,
    SettingsDesignTileGroup,
    SettingsDesignTileBgType,
    SettingsDesignTileSolid,
    SettingsDesignTileGradient,
    SettingsDesignTileTransparent,
    SettingsDesignTileBg,
    SettingsDesignTileGradEnd,
    SettingsDesignTileAngle,
    SettingsDesignTileGlow,
    SettingsDesignTileGlowRadius,
    SettingsDesignThemeName,
    SettingsDesignApply,
    SettingsDesignExport,
    SettingsDesignImport,
    SettingsDesignExportTitle,
    SettingsDesignImportTitle,
    SettingsDesignExportOk,
    SettingsDesignExportErr,
    SettingsDesignImportOk,
    SettingsDesignImportErr,
    SettingsDesignProfileDark,
    SettingsDesignProfileDarkDesc,
    SettingsDesignProfileOLED,
    SettingsDesignProfileOLEDDesc,
    SettingsDesignProfileOcean,
    SettingsDesignProfileOceanDesc,
    SettingsDesignProfileInferno,
    SettingsDesignProfileInfernoDesc,
    SettingsDesignProfileNeon,
    SettingsDesignProfileNeonDesc,
    SettingsDesignProfileRose,
    SettingsDesignProfileRoseDesc,
    SettingsDesignProfileElegant,
    SettingsDesignProfileElegantDesc,
    SettingsDesignProfileSimple,
    SettingsDesignProfileSimpleDesc,
    SettingsDesignProfileCustom,
    SettingsDesignProfileCustomDesc,

    // Converter (Tag <-> Unterkategorie)
    ConverterTabTitle,
    ConverterTagToSubcat,
    ConverterSubcatToTag,
    ConverterSelectTag,
    ConverterSelectParentCat,
    ConverterSelectSubcat,
    ConverterNewSubcatName,
    ConverterConvert,
    ConverterSuccess,
    ConverterErrorNoTag,
    ConverterErrorNoCat,
    ConverterErrorNoSubcat,
    ConverterErrorNoName,
    ConverterMigrateJson,
    ConverterMigrateSuccess,
    ConverterMigrateError,
    ConverterMigrateConfirm,
};

class Strings {
public:
    static QString get(StringKey key);
    static QString get(StringKey key, const QString& arg1);

private:
    static const QString& de(StringKey key);
    static const QString& en(StringKey key);
};
