#include "Strings.h"
#include <QMap>

// ─────────────────────────────────────────────────────────────────────────────
// German strings
// ─────────────────────────────────────────────────────────────────────────────
static const QMap<StringKey, QString> s_de = {
    { StringKey::MenuFile,              "&Datei" },
    { StringKey::MenuView,              "&Ansicht" },
    { StringKey::MenuSettings,          "&Einstellungen" },
    { StringKey::MenuOpenFolder,        "Ordner öffnen…" },
    { StringKey::MenuRefresh,           "Neu laden (R)" },
    { StringKey::MenuQuit,              "Beenden" },
    { StringKey::MenuToggleOptions,     "Optionen ein/aus (S)" },
    { StringKey::MenuSettingsItem,      "Einstellungen…" },
    { StringKey::MenuLanguage,          "Sprache" },
    { StringKey::MenuVideoPlayback,     "Video-Wiedergabe" },
    { StringKey::MenuVideoNative,       "Nativ" },
    { StringKey::MenuVideoExternal,     "Externer Player" },
    { StringKey::StatusFolderLoaded,    "Ordner geladen: " },
    { StringKey::StatusRenamed,         "Umbenannt: " },

    { StringKey::FilterImages,          "Bilder" },
    { StringKey::FilterVideos,          "Videos" },
    { StringKey::FilterAudio,           "Audio" },
    { StringKey::FilterPdf,             "PDF" },
    { StringKey::FilterMedia,           "Medien" },
    { StringKey::FilterSortBy,          "Sortierung:" },
    { StringKey::FilterDate,            "Datum" },
    { StringKey::FilterName,            "Name" },
    { StringKey::FilterTags,            "Tags" },
    { StringKey::FilterFileSize,        "Dateigröße" },
    { StringKey::FilterReverseOrder,    "Reihenfolge umkehren" },
    { StringKey::FilterTagModeTooltip,  "Tag-Filter: UND = alle Tags müssen passen, ODER = mind. einer, NUR = ausschließlich diese, INKLUSIV = hat diesen Tag" },
    { StringKey::FilterTagModeAnd,      "UND" },
    { StringKey::FilterTagModeOr,       "ODER" },
    { StringKey::FilterTagModeNur,      "NUR" },
    { StringKey::FilterTagModeInklusiv, "INKLUSIV" },

    { StringKey::FullscreenBack,               "← Zurück" },
    { StringKey::FullscreenFilenamePlaceholder,"Dateiname…" },
    { StringKey::FullscreenEditDate,           "Datum bearbeiten (D)" },
    { StringKey::FullscreenPrev,               "◀ Vorherige" },
    { StringKey::FullscreenNext,               "Nächste ▶" },
    { StringKey::FullscreenRandom,             "🔀 Zufall" },
    { StringKey::FullscreenImageLoadError,     "Bild konnte nicht geladen werden" },

    { StringKey::SettingsTitle,         "Einstellungen" },
    { StringKey::SettingsTabGeneral,    "Allgemein" },
    { StringKey::SettingsTabTags,       "Tags" },
    { StringKey::SettingsTabDesign,     "Design" },
    { StringKey::SettingsLanguageGroup, "Sprache / Language" },
    { StringKey::SettingsLanguageLabel, "Sprache:" },
    { StringKey::SettingsVideoGroup,    "Video-Wiedergabe" },
    { StringKey::SettingsVideoNative,   "Nativ (eingebetteter Player)" },
    { StringKey::SettingsVideoExternal, "Externer Player" },
    { StringKey::SettingsColorsGroup,   "Farben" },
    { StringKey::SettingsColorBg,       "Hintergrundfarbe:" },
    { StringKey::SettingsColorAccent,   "Akzentfarbe:" },
    { StringKey::SettingsColorAndOr,    "UND/ODER-Button:" },
    { StringKey::SettingsColorReset,    "Standard wiederherstellen" },
    { StringKey::SettingsOk,            "OK" },
    { StringKey::SettingsCancel,        "Abbrechen" },
    { StringKey::SettingsTagsHint,      "Tags verwalten: Farbe ändern, umbenennen oder Tag löschen." },
    { StringKey::SettingsTagChangeColor,"Farbe ändern" },
    { StringKey::SettingsTagDelete,     "Tag löschen" },
    { StringKey::SettingsTagDeleteTitle,"Tag löschen" },
    { StringKey::SettingsTagDeleteMsg,  "Tag \"%1\" wirklich löschen?\nEr wird aus allen Dateien entfernt." },
    { StringKey::SettingsTagEmpty,      "Keine Tags vorhanden." },

    { StringKey::MetaTitle,         "Datum bearbeiten" },
    { StringKey::MetaFile,          "Datei: " },
    { StringKey::MetaDate,          "Datum:" },
    { StringKey::MetaUseCustomDate, "Benutzerdefiniertes Datum verwenden" },
    { StringKey::MetaReset,         "Zurücksetzen" },
    { StringKey::MetaOk,            "OK" },
    { StringKey::MetaCancel,        "Abbrechen" },

    { StringKey::TagBarPlaceholder,     "Tag hinzufügen…" },
    { StringKey::TagBarDropdownTooltip, "Existierenden Tag auswählen" },
    { StringKey::TagBarDropdownHeader,  "Tag hinzufügen" },
    { StringKey::TagBarNoTags,          "(Keine Tags vorhanden)" },
    { StringKey::TagBarCompactTooltip,  "Tags hinzufügen / anzeigen" },

    { StringKey::CatPanelAddCategory,   "Neue Kategorie" },
    { StringKey::CatPanelNewSubcategory,"Neue Unterkategorie" },
    { StringKey::CatPanelRename,        "Umbenennen" },
    { StringKey::CatPanelDelete,        "Kategorie löschen" },
    { StringKey::CatPanelDeleteMsg,     "Kategorie \"%1\" wirklich löschen?\nEnthaltene Tags bleiben erhalten." },
    { StringKey::CatPanelSetColor,      "Einheitsfarbe setzen" },
    { StringKey::CatPanelAddTag,        "Zu Kategorie hinzufügen" },
    { StringKey::CatPanelNewTag,        "Neuer Tag" },
    { StringKey::CatPanelAddToTagMode,  "Add-to-Tag Modus: \"%1\"…" },
    { StringKey::CatPanelGroupMode,     "Gruppenauswahl: \"%1\"…" },

    { StringKey::BannerGroupMode,          "🗂  Gruppenauswahl: Tag \"%1\"  —  Rechtsklick zum Ändern der Tag-Zuordnung" },
    { StringKey::BannerGroupModeCancel,    "✕  Abbrechen" },
    { StringKey::BannerAddToTagMode,       "🏷  Add-to-Tag Modus: \"%1\"  —  Linksklick zum Hinzufügen / Entfernen" },
    { StringKey::BannerAddToTagModeCancel, "✕  Abbrechen" },

    { StringKey::FilterAddCategory,     "Neue Kategorie erstellen" },
    { StringKey::FilterNewCategory,     "Neue Kategorie" },
    { StringKey::FilterCategoryColor,   "Kategoriefarbe" },
    { StringKey::FilterNoCategories,    "(Keine Kategorien vorhanden)" },
    { StringKey::FilterNoTags,          "(Keine Tags vorhanden)" },
    { StringKey::FilterModePanelHeader, "Filtermodus" },
    { StringKey::FilterModeOrTip,       "Mind. ein Tag muss passen" },
    { StringKey::FilterModeAndTip,      "Alle Tags müssen passen" },
    { StringKey::FilterModeNurTip,      "Ausschließlich diese Tags – keine anderen" },
    { StringKey::FilterModeInklusivTip, "Hat diesen Tag (weitere erlaubt)" },
    { StringKey::FilterCatRename,       "✏  Umbenennen" },
    { StringKey::FilterCatRenamePrompt, "Umbenennen" },
    { StringKey::FilterCatNewName,      "Neuer Name:" },
    { StringKey::FilterCatChangeColor,  "🎨  Farbe ändern" },
    { StringKey::FilterNewTag,          "+ Neuer Tag…" },
    { StringKey::FilterNewTagLabel,     "Tag-Name:" },
    { StringKey::FilterCatAddSub,       "+ Unterkategorie" },
    { StringKey::FilterCatNewSubPrompt, "Neue Unterkategorie" },
    { StringKey::FilterCatDelete,       "🗑  Kategorie löschen" },
    { StringKey::FilterTagRename,       "✏  Umbenennen" },
    { StringKey::FilterTagRenamePrompt, "Tag umbenennen" },
    { StringKey::FilterTagNewName,      "Neuer Name:" },
    { StringKey::FilterTagAlreadyIn,    "✓ Bereits in \"%1\"" },
    { StringKey::FilterTagAddTo,        "Zu \"%1\" hinzufügen" },

    { StringKey::SettingsTabCategories,  "Kategorien" },
    { StringKey::SettingsCatHint,        "Kategorien, Unterkategorien und ihre Tags verwalten." },
    { StringKey::SettingsCatAdd,         "+ Kategorie" },
    { StringKey::SettingsCatEmpty,       "(Keine Kategorien vorhanden)" },
    { StringKey::SettingsCatNewTitle,    "Neue Kategorie" },
    { StringKey::SettingsCatNewLabel,    "Name:" },
    { StringKey::SettingsCatColorTitle,  "Kategoriefarbe" },
    { StringKey::SettingsCatRenameTitle, "Kategorie umbenennen" },
    { StringKey::SettingsCatRenameLabel, "Neuer Name:" },
    { StringKey::SettingsCatDeleteTitle, "Kategorie löschen" },
    { StringKey::SettingsCatDeleteMsg,   "Kategorie \"%1\" wirklich löschen?\nTags bleiben erhalten." },
    { StringKey::SettingsSubNewTitle,    "Neue Unterkategorie" },
    { StringKey::SettingsSubNewLabel,    "Name:" },
    { StringKey::SettingsSubColorTitle,  "Farbe der Unterkategorie" },
    { StringKey::SettingsTagRenameTitle, "Tag umbenennen" },
    { StringKey::SettingsTagRenameLabel, "Neuer Name:" },
    { StringKey::SettingsTagAdd,         "+ Tag" },
    { StringKey::SettingsTagNewTitle,    "Neuer Tag" },
    { StringKey::SettingsTagNewLabel,    "Tag-Name:" },
    { StringKey::SettingsTagColorTitle,  "Tag-Farbe" },

    { StringKey::SettingsDesignProfileGroup,    "Design-Profile" },
    { StringKey::SettingsCustomThemeEditor,     "Eigener Theme-Editor" },
    { StringKey::SettingsDesignBaseColors,      "Grundfarben" },
    { StringKey::SettingsDesignColorBg2,        "Hintergrund:" },
    { StringKey::SettingsDesignColorCard,       "Karte:" },
    { StringKey::SettingsDesignColorText,       "Text:" },
    { StringKey::SettingsDesignColorMuted,      "Text (gedämpft):" },
    { StringKey::SettingsDesignColorBorder,     "Rahmen:" },
    { StringKey::SettingsDesignBgGradient,      "Hintergrund-Verlauf" },
    { StringKey::SettingsDesignBgGradientEnable,"Verlaufshintergrund aktivieren" },
    { StringKey::SettingsDesignGradStart,       "Verlauf Start:" },
    { StringKey::SettingsDesignGradEnd,         "Verlauf Ende:" },
    { StringKey::SettingsDesignAngle,           "Winkel:" },
    { StringKey::SettingsDesignAccent,          "Akzent" },
    { StringKey::SettingsDesignType,            "Typ:" },
    { StringKey::SettingsDesignAccentSolid,     "Einfarbig" },
    { StringKey::SettingsDesignAccentGradient,  "Verlauf" },
    { StringKey::SettingsDesignAccentGlow,      "Glühen" },
    { StringKey::SettingsDesignAccentColor,     "Akzentfarbe:" },
    { StringKey::SettingsDesignGlowRadius,      "Glühradius:" },
    { StringKey::SettingsDesignGlowIntensity,   "Glühstärke:" },
    { StringKey::SettingsDesignTileGroup,       "Kachel-Hintergrund (Vorschaukarten)" },
    { StringKey::SettingsDesignTileBgType,      "Typ:" },
    { StringKey::SettingsDesignTileSolid,       "Einfarbig" },
    { StringKey::SettingsDesignTileGradient,    "Verlauf" },
    { StringKey::SettingsDesignTileTransparent, "Transparent" },
    { StringKey::SettingsDesignTileBg,          "Hintergrund:" },
    { StringKey::SettingsDesignTileGradEnd,     "Verlauf Ende:" },
    { StringKey::SettingsDesignTileAngle,       "Verlaufswinkel:" },
    { StringKey::SettingsDesignTileGlow,        "Glühen beim Hover" },
    { StringKey::SettingsDesignTileGlowRadius,  "Hover-Glühradius:" },
    { StringKey::SettingsDesignThemeName,       "Theme-Name:" },
    { StringKey::SettingsDesignApply,           "✓  Eigenes Theme anwenden" },
    { StringKey::SettingsDesignExport,          "⬆  Exportieren…" },
    { StringKey::SettingsDesignImport,          "⬇  Importieren…" },
    { StringKey::SettingsDesignExportTitle,     "Theme exportieren" },
    { StringKey::SettingsDesignImportTitle,     "Theme importieren" },
    { StringKey::SettingsDesignExportOk,        "Theme gespeichert:\n" },
    { StringKey::SettingsDesignExportErr,       "Datei konnte nicht geschrieben werden." },
    { StringKey::SettingsDesignImportOk,        "Theme geladen: " },
    { StringKey::SettingsDesignImportErr,       "Theme-Datei konnte nicht gelesen werden." },
    { StringKey::SettingsDesignProfileDark,         "Dark" },
    { StringKey::SettingsDesignProfileDarkDesc,     "Teal auf Dunkelblau (Standard)" },
    { StringKey::SettingsDesignProfileOLED,         "Dark OLED" },
    { StringKey::SettingsDesignProfileOLEDDesc,     "Reines Schwarz, leuchtendes Cyan" },
    { StringKey::SettingsDesignProfileOcean,        "Meerestiefe" },
    { StringKey::SettingsDesignProfileOceanDesc,    "Schwarz → tiefes Ozeanblau" },
    { StringKey::SettingsDesignProfileInferno,      "Inferno" },
    { StringKey::SettingsDesignProfileInfernoDesc,  "Schwarz → tiefes Orange / Bernstein" },
    { StringKey::SettingsDesignProfileNeon,         "Neon-Lila" },
    { StringKey::SettingsDesignProfileNeonDesc,     "Fast Schwarz, elektrisch-violettes Glühen" },
    { StringKey::SettingsDesignProfileRose,         "Mitternachtsrose" },
    { StringKey::SettingsDesignProfileRoseDesc,     "Dunkel → Karmesinrot-Verlauf" },
    { StringKey::SettingsDesignProfileElegant,      "Elegant" },
    { StringKey::SettingsDesignProfileElegantDesc,  "Tiefes Violett, verfeinert" },
    { StringKey::SettingsDesignProfileSimple,       "Schlicht" },
    { StringKey::SettingsDesignProfileSimpleDesc,   "Neutrales Grau, minimalistisch" },
    { StringKey::SettingsDesignProfileCustom,       "Eigenes" },
    { StringKey::SettingsDesignProfileCustomDesc,   "Deine eigenen Farben" },

    // Converter
    { StringKey::ConverterTabTitle,       "Konverter" },
    { StringKey::ConverterTagToSubcat,    "Tag → Unterkategorie" },
    { StringKey::ConverterSubcatToTag,    "Unterkategorie → Tag" },
    { StringKey::ConverterSelectTag,      "Tag auswählen:" },
    { StringKey::ConverterSelectParentCat,"Eltern-Kategorie:" },
    { StringKey::ConverterSelectSubcat,   "Unterkategorie auswählen:" },
    { StringKey::ConverterNewSubcatName,  "Name der neuen Unterkategorie:" },
    { StringKey::ConverterConvert,        "Konvertieren" },
    { StringKey::ConverterSuccess,        "Konvertierung erfolgreich." },
    { StringKey::ConverterErrorNoTag,     "Bitte einen Tag auswählen." },
    { StringKey::ConverterErrorNoCat,     "Bitte eine Eltern-Kategorie auswählen." },
    { StringKey::ConverterErrorNoSubcat,  "Bitte eine Unterkategorie auswählen." },
    { StringKey::ConverterErrorNoName,    "Bitte einen Namen eingeben." },
    { StringKey::ConverterMigrateJson,    "JSON-Daten ins neue Format migrieren" },
    { StringKey::ConverterMigrateSuccess, "Migration erfolgreich abgeschlossen." },
    { StringKey::ConverterMigrateError,   "Migration fehlgeschlagen." },
    { StringKey::ConverterMigrateConfirm, "JSON-Daten neu schreiben? (Backup empfohlen)" },
};

// ─────────────────────────────────────────────────────────────────────────────
// English strings
// ─────────────────────────────────────────────────────────────────────────────
static const QMap<StringKey, QString> s_en = {
    { StringKey::MenuFile,              "&File" },
    { StringKey::MenuView,              "&View" },
    { StringKey::MenuSettings,          "&Settings" },
    { StringKey::MenuOpenFolder,        "Open Folder…" },
    { StringKey::MenuRefresh,           "Reload (R)" },
    { StringKey::MenuQuit,              "Quit" },
    { StringKey::MenuToggleOptions,     "Toggle Options (S)" },
    { StringKey::MenuSettingsItem,      "Settings…" },
    { StringKey::MenuLanguage,          "Language" },
    { StringKey::MenuVideoPlayback,     "Video Playback" },
    { StringKey::MenuVideoNative,       "Native" },
    { StringKey::MenuVideoExternal,     "External Player" },
    { StringKey::StatusFolderLoaded,    "Folder loaded: " },
    { StringKey::StatusRenamed,         "Renamed: " },

    { StringKey::FilterImages,          "Images" },
    { StringKey::FilterVideos,          "Videos" },
    { StringKey::FilterAudio,           "Audio" },
    { StringKey::FilterPdf,             "PDF" },
    { StringKey::FilterMedia,           "Media" },
    { StringKey::FilterSortBy,          "Sort by:" },
    { StringKey::FilterDate,            "Date" },
    { StringKey::FilterName,            "Name" },
    { StringKey::FilterTags,            "Tags" },
    { StringKey::FilterFileSize,        "File Size" },
    { StringKey::FilterReverseOrder,    "Reverse Order" },
    { StringKey::FilterTagModeTooltip,  "Tag filter: AND = all tags must match, OR = at least one, ONLY = exclusively these, INCLUSIVE = has this tag" },
    { StringKey::FilterTagModeAnd,      "AND" },
    { StringKey::FilterTagModeOr,       "OR" },
    { StringKey::FilterTagModeNur,      "ONLY" },
    { StringKey::FilterTagModeInklusiv, "INCLUSIVE" },

    { StringKey::FullscreenBack,               "← Back" },
    { StringKey::FullscreenFilenamePlaceholder,"File name…" },
    { StringKey::FullscreenEditDate,           "Edit Date (D)" },
    { StringKey::FullscreenPrev,               "◀ Previous" },
    { StringKey::FullscreenNext,               "Next ▶" },
    { StringKey::FullscreenRandom,             "🔀 Random" },
    { StringKey::FullscreenImageLoadError,     "Could not load image" },

    { StringKey::SettingsTitle,         "Settings" },
    { StringKey::SettingsTabGeneral,    "General" },
    { StringKey::SettingsTabTags,       "Tags" },
    { StringKey::SettingsTabDesign,     "Design" },
    { StringKey::SettingsLanguageGroup, "Language" },
    { StringKey::SettingsLanguageLabel, "Language:" },
    { StringKey::SettingsVideoGroup,    "Video Playback" },
    { StringKey::SettingsVideoNative,   "Native (built-in player)" },
    { StringKey::SettingsVideoExternal, "External Player" },
    { StringKey::SettingsColorsGroup,   "Colors" },
    { StringKey::SettingsColorBg,       "Background Color:" },
    { StringKey::SettingsColorAccent,   "Accent Color:" },
    { StringKey::SettingsColorAndOr,    "AND/OR Button:" },
    { StringKey::SettingsColorReset,    "Restore Defaults" },
    { StringKey::SettingsOk,            "OK" },
    { StringKey::SettingsCancel,        "Cancel" },
    { StringKey::SettingsTagsHint,      "Manage tags: change color, rename, or delete a tag entirely." },
    { StringKey::SettingsTagChangeColor,"Change color" },
    { StringKey::SettingsTagDelete,     "Delete tag" },
    { StringKey::SettingsTagDeleteTitle,"Delete Tag" },
    { StringKey::SettingsTagDeleteMsg,  "Really delete tag \"%1\"?\nIt will be removed from all files." },
    { StringKey::SettingsTagEmpty,      "No tags available." },

    { StringKey::MetaTitle,         "Edit Date" },
    { StringKey::MetaFile,          "File: " },
    { StringKey::MetaDate,          "Date:" },
    { StringKey::MetaUseCustomDate, "Use custom date" },
    { StringKey::MetaReset,         "Reset" },
    { StringKey::MetaOk,            "OK" },
    { StringKey::MetaCancel,        "Cancel" },

    { StringKey::TagBarPlaceholder,     "Add tag…" },
    { StringKey::TagBarDropdownTooltip, "Select existing tag" },
    { StringKey::TagBarDropdownHeader,  "Add tag" },
    { StringKey::TagBarNoTags,          "(No tags available)" },
    { StringKey::TagBarCompactTooltip,  "Add / view tags" },

    { StringKey::CatPanelAddCategory,   "New Category" },
    { StringKey::CatPanelNewSubcategory,"New Subcategory" },
    { StringKey::CatPanelRename,        "Rename" },
    { StringKey::CatPanelDelete,        "Delete Category" },
    { StringKey::CatPanelDeleteMsg,     "Really delete category \"%1\"?\nContained tags will be kept." },
    { StringKey::CatPanelSetColor,      "Set uniform color" },
    { StringKey::CatPanelAddTag,        "Add to category" },
    { StringKey::CatPanelNewTag,        "New tag" },
    { StringKey::CatPanelAddToTagMode,  "Add-to-Tag Mode: \"%1\"…" },
    { StringKey::CatPanelGroupMode,     "Group Mode: \"%1\"…" },

    { StringKey::BannerGroupMode,          "🗂  Group mode: Tag \"%1\"  —  Right-click to toggle tag membership" },
    { StringKey::BannerGroupModeCancel,    "✕  Cancel" },
    { StringKey::BannerAddToTagMode,       "🏷  Add-to-Tag Mode: \"%1\"  —  Left-click to add / remove" },
    { StringKey::BannerAddToTagModeCancel, "✕  Cancel" },

    { StringKey::FilterAddCategory,     "Create new category" },
    { StringKey::FilterNewCategory,     "New Category" },
    { StringKey::FilterCategoryColor,   "Category Color" },
    { StringKey::FilterNoCategories,    "(No categories available)" },
    { StringKey::FilterNoTags,          "(No tags available)" },
    { StringKey::FilterModePanelHeader, "Filter Mode" },
    { StringKey::FilterModeOrTip,       "At least one tag must match" },
    { StringKey::FilterModeAndTip,      "All tags must match" },
    { StringKey::FilterModeNurTip,      "Only exactly these tags — no others" },
    { StringKey::FilterModeInklusivTip, "Has this tag (others allowed)" },
    { StringKey::FilterCatRename,       "✏  Rename" },
    { StringKey::FilterCatRenamePrompt, "Rename" },
    { StringKey::FilterCatNewName,      "New name:" },
    { StringKey::FilterCatChangeColor,  "🎨  Change color" },
    { StringKey::FilterNewTag,          "+ New Tag…" },
    { StringKey::FilterNewTagLabel,     "Tag name:" },
    { StringKey::FilterCatAddSub,       "+ Subcategory" },
    { StringKey::FilterCatNewSubPrompt, "New Subcategory" },
    { StringKey::FilterCatDelete,       "🗑  Delete category" },
    { StringKey::FilterTagRename,       "✏  Rename" },
    { StringKey::FilterTagRenamePrompt, "Rename Tag" },
    { StringKey::FilterTagNewName,      "New name:" },
    { StringKey::FilterTagAlreadyIn,    "✓ Already in \"%1\"" },
    { StringKey::FilterTagAddTo,        "Add to \"%1\"" },

    { StringKey::SettingsTabCategories,  "Categories" },
    { StringKey::SettingsCatHint,        "Manage categories, subcategories and their tags." },
    { StringKey::SettingsCatAdd,         "+ Category" },
    { StringKey::SettingsCatEmpty,       "(No categories available)" },
    { StringKey::SettingsCatNewTitle,    "New Category" },
    { StringKey::SettingsCatNewLabel,    "Name:" },
    { StringKey::SettingsCatColorTitle,  "Category Color" },
    { StringKey::SettingsCatRenameTitle, "Rename Category" },
    { StringKey::SettingsCatRenameLabel, "New name:" },
    { StringKey::SettingsCatDeleteTitle, "Delete Category" },
    { StringKey::SettingsCatDeleteMsg,   "Really delete category \"%1\"?\nTags will be kept." },
    { StringKey::SettingsSubNewTitle,    "New Subcategory" },
    { StringKey::SettingsSubNewLabel,    "Name:" },
    { StringKey::SettingsSubColorTitle,  "Subcategory Color" },
    { StringKey::SettingsTagRenameTitle, "Rename Tag" },
    { StringKey::SettingsTagRenameLabel, "New name:" },
    { StringKey::SettingsTagAdd,         "+ Tag" },
    { StringKey::SettingsTagNewTitle,    "New Tag" },
    { StringKey::SettingsTagNewLabel,    "Tag name:" },
    { StringKey::SettingsTagColorTitle,  "Tag Color" },

    { StringKey::SettingsDesignProfileGroup,    "Design Profiles" },
    { StringKey::SettingsCustomThemeEditor,     "Custom Theme Editor" },
    { StringKey::SettingsDesignBaseColors,      "Base Colors" },
    { StringKey::SettingsDesignColorBg2,        "Background:" },
    { StringKey::SettingsDesignColorCard,       "Card:" },
    { StringKey::SettingsDesignColorText,       "Text:" },
    { StringKey::SettingsDesignColorMuted,      "Text (muted):" },
    { StringKey::SettingsDesignColorBorder,     "Border:" },
    { StringKey::SettingsDesignBgGradient,      "Background Gradient" },
    { StringKey::SettingsDesignBgGradientEnable,"Enable gradient background" },
    { StringKey::SettingsDesignGradStart,       "Gradient start:" },
    { StringKey::SettingsDesignGradEnd,         "Gradient end:" },
    { StringKey::SettingsDesignAngle,           "Angle:" },
    { StringKey::SettingsDesignAccent,          "Accent" },
    { StringKey::SettingsDesignType,            "Type:" },
    { StringKey::SettingsDesignAccentSolid,     "Solid" },
    { StringKey::SettingsDesignAccentGradient,  "Gradient" },
    { StringKey::SettingsDesignAccentGlow,      "Glow" },
    { StringKey::SettingsDesignAccentColor,     "Accent color:" },
    { StringKey::SettingsDesignGlowRadius,      "Glow radius:" },
    { StringKey::SettingsDesignGlowIntensity,   "Glow intensity:" },
    { StringKey::SettingsDesignTileGroup,       "Tile (Thumbnail Card) Background" },
    { StringKey::SettingsDesignTileBgType,      "Type:" },
    { StringKey::SettingsDesignTileSolid,       "Solid" },
    { StringKey::SettingsDesignTileGradient,    "Gradient" },
    { StringKey::SettingsDesignTileTransparent, "Transparent" },
    { StringKey::SettingsDesignTileBg,          "Background:" },
    { StringKey::SettingsDesignTileGradEnd,     "Gradient end:" },
    { StringKey::SettingsDesignTileAngle,       "Gradient angle:" },
    { StringKey::SettingsDesignTileGlow,        "Glow on hover" },
    { StringKey::SettingsDesignTileGlowRadius,  "Hover glow radius:" },
    { StringKey::SettingsDesignThemeName,       "Theme name:" },
    { StringKey::SettingsDesignApply,           "✓  Apply Custom Theme" },
    { StringKey::SettingsDesignExport,          "⬆  Export…" },
    { StringKey::SettingsDesignImport,          "⬇  Import…" },
    { StringKey::SettingsDesignExportTitle,     "Export Theme" },
    { StringKey::SettingsDesignImportTitle,     "Import Theme" },
    { StringKey::SettingsDesignExportOk,        "Theme saved to:\n" },
    { StringKey::SettingsDesignExportErr,       "Could not write file." },
    { StringKey::SettingsDesignImportOk,        "Theme loaded: " },
    { StringKey::SettingsDesignImportErr,       "Could not read theme file." },
    { StringKey::SettingsDesignProfileDark,         "Dark" },
    { StringKey::SettingsDesignProfileDarkDesc,     "Teal on dark blue (default)" },
    { StringKey::SettingsDesignProfileOLED,         "Dark OLED" },
    { StringKey::SettingsDesignProfileOLEDDesc,     "Pure black, glowing cyan" },
    { StringKey::SettingsDesignProfileOcean,        "Ocean Depth" },
    { StringKey::SettingsDesignProfileOceanDesc,    "Black → deep ocean blue" },
    { StringKey::SettingsDesignProfileInferno,      "Inferno Blaze" },
    { StringKey::SettingsDesignProfileInfernoDesc,  "Black → deep orange / amber" },
    { StringKey::SettingsDesignProfileNeon,         "Neon Purple" },
    { StringKey::SettingsDesignProfileNeonDesc,     "Near-black, electric violet glow" },
    { StringKey::SettingsDesignProfileRose,         "Midnight Rose" },
    { StringKey::SettingsDesignProfileRoseDesc,     "Dark → crimson rose gradient" },
    { StringKey::SettingsDesignProfileElegant,      "Elegant" },
    { StringKey::SettingsDesignProfileElegantDesc,  "Deep purple, refined" },
    { StringKey::SettingsDesignProfileSimple,       "Simple" },
    { StringKey::SettingsDesignProfileSimpleDesc,   "Neutral grey, minimal" },
    { StringKey::SettingsDesignProfileCustom,       "Custom" },
    { StringKey::SettingsDesignProfileCustomDesc,   "Your own colors" },

    // Converter
    { StringKey::ConverterTabTitle,       "Converter" },
    { StringKey::ConverterTagToSubcat,    "Tag → Subcategory" },
    { StringKey::ConverterSubcatToTag,    "Subcategory → Tag" },
    { StringKey::ConverterSelectTag,      "Select tag:" },
    { StringKey::ConverterSelectParentCat,"Parent category:" },
    { StringKey::ConverterSelectSubcat,   "Select subcategory:" },
    { StringKey::ConverterNewSubcatName,  "New subcategory name:" },
    { StringKey::ConverterConvert,        "Convert" },
    { StringKey::ConverterSuccess,        "Conversion successful." },
    { StringKey::ConverterErrorNoTag,     "Please select a tag." },
    { StringKey::ConverterErrorNoCat,     "Please select a parent category." },
    { StringKey::ConverterErrorNoSubcat,  "Please select a subcategory." },
    { StringKey::ConverterErrorNoName,    "Please enter a name." },
    { StringKey::ConverterMigrateJson,    "Migrate JSON data to new format" },
    { StringKey::ConverterMigrateSuccess, "Migration completed successfully." },
    { StringKey::ConverterMigrateError,   "Migration failed." },
    { StringKey::ConverterMigrateConfirm, "Rewrite JSON data? (Backup recommended)" },
};

// ─────────────────────────────────────────────────────────────────────────────
// Lookup
// ─────────────────────────────────────────────────────────────────────────────
QString Strings::get(StringKey key) {
    Language lang = AppSettings::instance().language();
    const QMap<StringKey, QString>& map = (lang == Language::English) ? s_en : s_de;
    return map.value(key, QStringLiteral("?"));
}

QString Strings::get(StringKey key, const QString& arg1) {
    return get(key).arg(arg1);
}
